### ISSUE TITLE
currently-inaccessible paths are removed

### ISSUE THREAD

**Issue by lilydjwg** [ajeetdsouza/zoxide#105]
A path that is currently inaccessible doesn't mean it isn't useful anymore, e.g. mount points. I mount my regular external disks at fixed mount points. I also create certain temporary directories with the same name every time I need them.

If an inaccessible path is found by zoxide, I prefer it to be skipped rather than be removed permanently. 

Also, currently-inaccessible paths can't be imported.

**Comment by ajeetdsouza** [comment]
That's a fair point. This should be default behavior.

**Comment by cole-h** [comment]
I wonder what kind of heuristic this would use. I really like that zoxide prunes unreachable directories, because chances are it's unreachable because it has been deleted... If it's just skipped, won't it be a valid target to jump to, if its score is high enough?

**Comment by ajeetdsouza** [comment]
@cole-h I'm thinking about this too. Say a directory is deleted:

- zoxide's current algorithm goes over directories in order of rank, and if it finds a match, it checks with the filesystem if that location is a directory. If it is, it will `cd` into it; otherwise, it will remove that entry and move on.

- If we just skip over the directory instead of removing it, the directory will start aging (since we never `cd` into it). The matching algorithm and filesystem check will almost never run on it, since it will have the lowest rank. Eventually, its score will fall below `1.0`, and it will be dropped out of the database.

The current lazy deletion algorithm can even be surprising at times. Say I access a directory called `foo` on my external hard disk. If I unplugged the hard disk and plugged it back in after making some zoxide queries, there is no way of knowing whether or not zoxide would remember `foo`. The only correct way to prune all unreachable directories is to force zoxide to list everything in the database (`zoxide query -l`).

Removing lazy deletion would not hurt performance except in some very specific scenarios. Even then, it would not be noticeable if `_ZO_MAXAGE` is set to a sensible value. However, it prevents surprising behavior, and I'd love to be able to reliably use zoxide with my external hard drive.

**Comment by ajeetdsouza** [comment]
The difference is: with the newly proposed algorithm, if I remove a directory, run some zoxide queries, and create it again, that directory will retain its old score. The current algorithm may either retain the old score or forget it entirely, based on the queries made.

**Comment by cole-h** [comment]
Thanks for the explanation; I'm a fan of the new algorithm, as described.

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/commit/f230e75559c82d056593fe4b0781de5f97caacee.

**Comment by ajeetdsouza** [comment]
Released in zoxide 0.5.0.
