### ISSUE TITLE
Is there a way to set default z behavior?

### ISSUE THREAD

**Issue by anki-code** [ajeetdsouza/zoxide#117]
Hi! subj

I have an experience with [autojump](https://github.com/wting/autojump): when I type just `j` it just go to the recently used or most used directory (I don't exactly know how it works).

Does `z` have something like this?

My use case of it is ssh. When I open the session I'm in home directory by default. Then I run `j` and I'm in the latest used directory without remembering it. If the the directory is wrong I run `j` again and in my experience after 2-3 tries of `j` without directory I'm in the right place and it was faster than remember the right path )

Thanks!

**Comment by ajeetdsouza** [comment]
`z` is designed to be a superset of the `cd` command. Running `z` without arguments would be equivalent to just running `cd`, which would take you to your home directory.

> in my experience after 2-3 tries of j without directory I'm in the right place

I'm not quite sure how that works. How is autojump maintaining state between `j` calls? Currently, `cd "$(zq)"` would take you to the highest ranked directory, but calling it again will simply take you to the same directory again.

IMO, this behaviour should probably be changed slightly - if I'm in `/tmp/foo` and I query for `foo`, I probably don't want to be taken to `/tmp/foo` again. Still, that would mean you can call `z` twice, after which you would just be jumping between the top two directories.

**Comment by anki-code** [comment]
I deep dive into autojump cache and found that it works as you suppose :)

>  Still, that would mean you can call z twice, after which you would just be jumping between the top two directories.

Calling `j` without arguments jump to the highest rank directory then to the second and then back to the highest.

**Comment by Qu4tro** [comment]
Would having a `zn` and `zp` (for next and previous respectively), that would allow to traverse the directories by rank, be an acceptable solution?

That way, `zn` could be aliased to `j` to have the behavior wanted here.

**Comment by anki-code** [comment]
Hi @Qu4tro! I have an error:
```bash
lsb_release -a
#Ubuntu 20.04.1
zoxide -V
#zoxide v0.5.0
tail -n 1 ~/.bashrc
# eval "$(zoxide init bash)"
z
zp
#zp: command not found
zn
#zn: command not found
```

**Comment by Qu4tro** [comment]
Hey there. I was just adding a suggestion. AFAIK there is no such feature at the moment.

**Comment by cho-m** [comment]
There seems to be 2 different ideas here.

---

The simpler idea is just jumping to highest ranking directory that is not the current.
Skimming through autojump, this may be closer to [what is done](https://github.com/wting/autojump/blob/06e082c91805cb022900819b2e0881eeae780d58/bin/autojump#L306) as it just looks for next match:
```python
def main(args):  # noqa
    ...
        print_local(first(chain(
            imap(attrgetter('path'), find_matches(entries, [''])),
            # always return a path to calling shell functions
            ['.'],
        )))

def find_matches(entries, needles, check_entries=True):
    ...
        lambda entry: not is_cwd(entry) and path_exists(entry),
```

For zoxide, this appears to be something planned based on author's comment both here and in the newer issue #139 

The poor-man's workaround would be to use some extra shell logic.
For POSIX shells, a limited option could be something like:
```sh
cd "$(zq --list 2>/dev/null | grep -v "^$PWD$" | head -1)"
```
A better version would probably check directory exists, resolve symlinks rather than just check `pwd` and maybe use a default directory.

---

The second idea is the ability to keep moving through zoxide's list, which would require additional state to support.

The behavior here is more open-ended, so it may be better to write your own shell functions to support what you exactly want.

A hacked up (probably buggy) example for Bash/Zsh that uses variables to move through the top 20 entries could be:
```sh
function j() {
  if [ "$#" -eq 0 ]; then
    if [ -z "$_ZO_CURRENT" ] || [ -z "$_ZO_SNAPSHOT" ] || [ "$_ZO_CURRENT" != "$PWD" ]; then
      _ZO_SNAPSHOT=$(zq --list 2>/dev/null | head -n 20)
    fi

    _ZO_CURRENT=""
    while [ -n "$_ZO_SNAPSHOT" ] && [ -z "$_ZO_CURRENT" ]; do
      _ZO_CURRENT=$(printf '%s' "$_ZO_SNAPSHOT" | head -n 1)
      _ZO_SNAPSHOT=$(printf '%s' "$_ZO_SNAPSHOT" | tail -n +2)
      if [ ! -d "$_ZO_CURRENT" ]; then
        _ZO_CURRENT=""
      fi
    done
    cd "${_ZO_CURRENT:-$HOME}"
  else
    z "$@"
  fi
}
```

**Comment by anki-code** [comment]
Hi @cho-m ! Thank you for your notes with commands examples

> cd "$(zq --list 2>/dev/null | grep -v "^$PWD$" | head -1)"
> A better version would probably check directory exists, resolve symlinks rather than just check pwd and maybe use a default directory.

Oh, very simple task for xonsh and to solve it I will not Googling and can write it with features you described::

```python
def _smart_z():
    z_dirs = [p for p in $(zq --list 2>/dev/null).splitlines() if $PWD != p and pf'{p}'.exists()]
    cd @(z_dirs[0] if z_dirs else $PWD)
aliases['z'] = _smart_z
```
(resolving symlinks to check exists is under the hood)

Thanks I'm happy and going from autojump to zoxide completely!

**Comment by ajeetdsouza** [comment]
> A better version would probably check directory exists, resolve symlinks rather than just check pwd and maybe use a default directory.

zoxide already checks if the directory exists before printing it out. Symlinks are resolved when zoxide stores the directory itself, so that should be fine too. They are resolved logically (similar to `realpath -ms` on Linux) - if you want full path canonicalization (useful on case-insensitive filesystems like on Windows), you can set `_ZO_RESOLVE_SYMLINKS=1`.
