### ISSUE TITLE
zoxide on NetBSD

### ISSUE THREAD

**Issue by voidpin** [ajeetdsouza/zoxide#124]
Hi,
I've just packaged and pushed `zoxide` to pkgsrc-current, https://mail-index.netbsd.org/pkgsrc-changes/2020/11/23/msg224287.html

This means that `zoxide` is now available on NetBSD.

To install on NetBSD you just need to run

`pkgin install zoxide`

or, if you prefer to build from source

```
cd /usr/pkgsrc/textproc/zoxide
make install

```

Please feel free to update the README.md file.

**Comment by ajeetdsouza** [comment]
@voidpin this is great, thank you! I don't have NetBSD to test this, but I'm not seeing it on [`pkgsrc/current`](http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/README-all.html). The website may not be updated yet, I'll put this up on the README as soon as it appears over there.

Also, just a thought - other distributions list `zoxide` under `sysutils`. You might want to consider changing it from `textproc` in order to avoid confusion.

**Comment by voidpin** [comment]
@ajeetdsouza initially, I had it under `sysutils` but, than I saw `bat` was in `textproc`, hence I move it there. If people complain, I'll change it.

As for the package, its there now, https://pkgsrc.se/textproc/zoxide

I'm using `zoxide` myself, it's nice, thanks.

**Comment by voidpin** [comment]
@ajeetdsouza FYI, I'm right now discussing the move from `textproc` to `sysutils`.
Thanks!

**Comment by ajeetdsouza** [comment]
Great! Let me know once it's moved.

**Comment by voidpin** [comment]
@ajeetdsouza `zoxide` has now been moved to `sysutils`, https://pkgsrc.se/sysutils/zoxide

**Comment by voidpin** [comment]
@ajeetdsouza Closing this issue now. The package is in `sysytils/zoxide` and it's reflected in **Repology**.

**Comment by ajeetdsouza** [comment]
@voidpin I've added this to the README. Thanks for maintaining zoxide!
