### ISSUE TITLE
Request: Support for Elvish

### ISSUE THREAD

**Issue by jacostag** [ajeetdsouza/zoxide#151]
I'd love to be able to use Elvish from https://elv.sh/

**Comment by gretel** [comment]
me too! thanks.

**Comment by PanAeon** [comment]
Hi, I've created the following script for the elvish:
```
after-chdir = [[dir]{ zoxide add (pwd -L) }]

fn _z_cd [directory]{
  cd $directory
}

fn zi [@a]{
  _z_cd (zoxide query -i -- $@a)
}

fn za [@a]{ zoxide add $@a }
fn zq [@a]{ zoxide query $@a }
fn zqi [@a]{ zoxide query -i $@a }

fn zr [@a]{ zoxide remove $@a }

fn zri [@a]{
  zoxide remove (zoxide query -i -- $@a)
}

fn z [@a]{
  if (is [] $@a) {
    _z_cd ~
  } else {
    # ok `z -` is not supported
    _z_cd (zoxide query -- $@a)
  }
}
```
It's a bit raw, but it works. The only thing is missing `z -` because elvish doesn't have support for that (I hope yet).
If I have time and energy I'll submit a proper pull request with a template.

**Comment by gretel** [comment]
@PanAeon thanks, it's working fine for me!

**Comment by ajeetdsouza** [comment]
Thanks, @PanAeon! `z -` is possible to do:

```shell
# setup
set-env __zoxide_oldpwd $pwd
before-chdir = [[_]{ set-env __zoxide_oldpwd $pwd }]

# z -
cd (get-env __zoxide_oldpwd)
```

---

I'm not familiar with Elvish, but here's a rough list of things that still need to be done before we can fully support it:

- [ ] If `z` gets only one argument, and that argument is a valid path, cd into it. [`is_dir`](https://elv.sh/ref/path.html#pathis-dir) will be useful here. Here's what this looks like in Xonsh:
   ```python
   if args == []:
        __zoxide_cd()
    elif args == ["-"]:
        __zoxide_cd("-")
    elif len(args) == 1 and os.path.isdir(args[0]): # <--- we need this
        __zoxide_cd(args[0])
    else:
        ...
    ```   
- [ ] Prompt hook - some users may want to trigger `zoxide add` on every prompt, rather than `after-chdir`. It would be nice if we could figure out how to do this.
- [ ] We need to _append_ zoxide functions to `before-chdir` and `after-chdir` rather than override the previous value.
