### ISSUE TITLE
Tracking the latest Zoxided directory.

### ISSUE THREAD

**Issue by yassinebridi** [ajeetdsouza/zoxide#159]
I'm using zoxide inside of [lf](https://github.com/gokcehan/lf), And i want to be able to zoxide into a directory, and then get back to the directory before.
Is it possible to track the latest directory that zoxide cded into?

**Comment by ajeetdsouza** [comment]
Hey @yassinebridi,

zoxide itself does not keep track of your last cd-ed directory. That would be hard to do, since zoxide could be running simultaneously in multiple terminals, and each of them would have their own last directory.

When using zoxide in shells, `z -` is able to take you to the previous directory because it uses an environment variable to keep track of the last cd-ed directory. Does lf allow you to do something like that?

**Comment by yassinebridi** [comment]
In the lf wiki they say that autojump relies on the shell prompt to update the database, i wonder if zoxide is the same, if it is i don't think my trick would work.

**Comment by ajeetdsouza** [comment]
The shell does tell zoxide when to update the database - either on every directory change, or on every prompt (configurable). You can update it manually too (see `zoxide add --help`).

I don't think it would make sense to update zoxide every time you move between directories in a file explorer like lf, but you might want to write your own `z args` function that looks like this:

- If `len(args) == 1` and `arg[0]` is a directory, cd into it and call `zoxide add`.
- Otherwise, use `zoxide query args` to find a match and then call `zoxide add`.
