### ISSUE TITLE
Use XDG_CACHE_HOME/zo as default database location

### ISSUE THREAD

**Issue by iulianR** [ajeetdsouza/zoxide#16]
Hi, great job on your tool!

I know you can configure the database location using `$_ZO_DATA`, but as a possible enhancement, I hope you will consider setting the default to `XDG_CACHE_HOME/zo` for the people that use the tool with default settings.

https://wiki.archlinux.org/index.php/XDG_Base_Directory#Specification
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Thanks!

**Comment by ajeetdsouza** [comment]
How would you handle this on macOS (and Windows, if it ever gets support)?

**Comment by iulianR** [comment]
I think you can have a look at this crate: https://docs.rs/dirs/2.0.2/dirs/. For example, https://docs.rs/dirs/2.0.2/dirs/fn.cache_dir.html says that `$HOME/Library/Caches` is used on macOS and that corresponds to the [Apple docs](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6). You don't really have to use the crate as you only care about `XDG_CACHE_HOME`.

Even if the change seems small, a small problem you're going to have is that some users already built up a database and you might have to consider a database "migration" on first boot, which is not really great as you might be stuck with the migration code for a long time. So I understand if you're not eager to make the change.

**Comment by ajeetdsouza** [comment]
True. The change is very simple to make without a migration, (only 1 line of code), but expecting the users to either move their database or have their cache deleted is not great. For now, I'm closing the issue until a better way of going about it is found.

Thanks!

**Comment by desbma** [comment]
> but expecting the users to either move their database or have their cache deleted is not great.

I think the format of the database has already changed once, which forced users to remove their database.

IMO you should implement this change as soon as possible, because when you get more users and the releases become more stable, it will become very hard to change (Firefox still uses ~/.mozilla for the only reason they can not change it anymore)

**Comment by ajeetdsouza** [comment]
@desbma I understand where you're coming from. The change in DB format was from `v0.1` to `v0.2`, before `zoxide` was released. Let's see if we can do this for the big `v1.0` release!

**Comment by cole-h** [comment]
If the plan is to leave this for `v1.0`, I would reopen this, but tag it as a `breaking change` and add it to the 1.0 milestone (creating one if you don't have one). This way, people know it has been considered, but won't happen for a while.

As a side note: in pre-1.0, semver allows breaking changes at any time -- see: https://semver.org/#spec-item-4. I understand your hesitation, but, IMHO, it's better to get these types of things over with sooner rather than later.

Additionally, this doesn't have to be a breaking change: just look for `$XDG_CACHE_HOME/zo`, `$HOME/.cache/zo`, and finally `$HOME/.zo` as a fallback path, creating it at `$XDG_CACHE_HOME/zo` (or `$HOME/.cache/zo` if that env var is undefined) if it doesn't exist anywhere. Then, current users won't lose all their data, and for new users, we will conform to the XDG Base Directory specification (or even old users who opt to move their database).

**Comment by ajeetdsouza** [comment]
That's a good idea. Reopened.

**Comment by ajeetdsouza** [comment]
This has been added in https://github.com/ajeetdsouza/zoxide/pull/46/commits/0617571807c461df094ad5e8dc95a154a587db65, and will be released with `zoxide v0.3`!
