### ISSUE TITLE
Bash Error message on Debian

### ISSUE THREAD

**Issue by ixzh** [ajeetdsouza/zoxide#169]
Hi,

When using with tmux there is this persistent error I don't know how to address:

```bash
-bash: PROMPT_COMMAND: line 59: syntax error near unexpected token `;'
-bash: PROMPT_COMMAND: line 59: `history -a; history -a; history -a; ;__zoxide_hook'
```
This message repeats after every command, with number  increasing (randomly?)

PS: And I can't find a clean way to uninstall zoxide. Can you include Uninstall section in the Readme? Thanks

**Comment by ajeetdsouza** [comment]
Hi @ixzh, sorry you had that experience.

The problem seems to be that your `PROMPT_COMMAND` variable ends with a semicolon. Once you remove the semicolon from the end, everything should work fine. I've created a PR to append `__zoxide_hook` to the _front_ of the variable instead, which should prevent this from happening in future.

Removing zoxide from your configuration is just a matter of removing the `eval "$(zoxide init bash)"` statement from your bashrc. Getting rid of the program itself depends on what package manager you used to install it. If you used the install script, then just locate the binary using `which zoxide`, and `rm` it.

**Comment by ixzh** [comment]
THank you!! will close the issue
