### ISSUE TITLE
zoxide changes db.zo ownership to root when using sudo -E

### ISSUE THREAD

**Issue by adrinux** [ajeetdsouza/zoxide#181]
Just revamped my zsh shell setup and included zoxide, it's fantastic!

But when I want to run a string of commands or move around the nether regions of my manjaro linux filesystem as **root** I'm in the habit of using `sudo -E zsh`, which carries over my user account shell setup to root.

However I've noticed that if I do that now and cd to a directory zoxide will happily store the history _but_ will change the ownership of `/home/adrinux/.local/share/zoxide/db.zo` to **root**.
Once I exit from root back to a normal user I then get permission denied errors from zoxide, for obvious reasons.

The fix is easy enough - just sudo chown it back to myself.

The workarounds are obvious: don't use sudo -E; just use sudo -s and put up with the suckier shell; or not and copy my shell config to the root user so it's the same, or even just use sudo for every command.

But at the same time I get the feeling zoxide shouldn't be quite so aggressive about changing the zo.db ownership to root, am I wrong?

For complete clarity here is an example session, assuming you've been using zoxide as a normal user so zo.db exists:
```bash
# check permissions
ls -al /home/adrinux/.local/share/zoxide
.rw------- 427 adrinux adrinux 13 Apr 15:39   db.zo
# switch to root and do some stuff
sudo -E zsh
cd /etc/systemd/system
exit
# back to our normal user and check permissions
ls -al /home/adrinux/.local/share/zoxide
.rw------- 470 root root 13 Apr 15:58    db.zo

# and the fix
sudo chown -R adrinux:adrinux /home/adrinux/.local/share/zoxide
```

**Comment by ajeetdsouza** [comment]
Hey @adrinux, thanks for reporting this. I don't think there's a straightforward solution to the issue, unfortunately.

- The owner on the file is changing because zoxide updates the database by creating a tempfile and atomically moving it over the original. The tempfile is always created under the current user (in your case, `root`). Editing the file in-place would fix the problem, but we would no longer have atomicity on the database, leading to possible corruption.
- We could change the permissions on the database file to `0666`. The problem with this approach is that users may not want their directory history to be accessible by everyone.

You could work around this by editing your `.zshrc` file to only call `zoxide init` when `$USER` is the correct user.

**Comment by adrinux** [comment]
Thanks @ajeetdsouza for the explanation - and a solution I hadn't yet thought of!

I think what I'll do is set up the shell for the root user how I like it and go back to using `sudo -s` to switch, that way root will have its own db.zo and I can still take advantage of the power :)

**Comment by ajeetdsouza** [comment]
@adrinux sounds good! If you're willing to have a separate DB for root, you can still use `sudo -E`:

```sh
if [ "$USER" = "root" ]; then
    export _ZO_DATA_DIR="/root/.local/share/zoxide"
fi

eval "$(zoxide init zsh)"
```

**Comment by magnetophon** [comment]
Hi @ajeetdsouza, thanks for zoxide, wonderful software!

> I don't think there's a straightforward solution to the issue, unfortunately.

While discussing this over at [zsh4humans](https://github.com/romkatv/zsh4humans/issues/185), the following solution was suggested by @romkatv:



Here's how one can "atomically" append to a file without changing its mode and permissions:
```shell
cp -p foo foo.tmp
echo extra >>foo.tmp
mv -f foo.tmp foo
```
I realize that zoxide is implemented in rust but this doesn't make the task any harder.
