### ISSUE TITLE
[FR] Add `zoxide query --list-fast`

### ISSUE THREAD

**Issue by NightMachinary** [ajeetdsouza/zoxide#182]
I use my own "frontend" to jump between dirs, and I just zoixide's functionality of remembering directories I have been to. The problem is that `zoxide query --list` is not optimized to be fast; It seems to process the whole db and check whether dirs exist or not etc. I want a `zoxide query --list-fast` that just lists all the dirs, sorted by their score, as fast as possible.

**Comment by ajeetdsouza** [comment]
@NightMachinary, to clarify:

- You don't want to check if the directory exists before printing
- You don't want any keyword matching

Is that correct? If so, could you describe how you're handling the result?

**Comment by NightMachinary** [comment]
[**@Ajeet D'Souza**](https://github.com/ajeetdsouza) commented on [Apr 14, 2021, 5:47 PM GMT+4:30](https://github.com/ajeetdsouza/zoxide/issues/182#issuecomment-819510826 "2021-04-14T13:17:21Z - Replied by Github Reply Comments"):
> [@NightMachinary](https://github.com/NightMachinary), to clarify:
> 
> *   You don't want to check if the directory exists before printing
> *   You don't want any keyword matching
> 
> Is that correct? If so, could you describe how you're handling the result?

Correct. I am piping all the dirs into fzf, and fzf handles the matching (most of the score functionality is unfortunately lost, as fzf only considers the order of the input when its own algorithm "ties", but this hasn't been very noticeable in my usage.). I cache the chosen directory myself into redis. The whole thing can be found [here](https://github.com/NightMachinary/.shells/blob/master/scripts/zshlang/interactive/auto-load/fuzzy/z.zsh), in case anyone wants to adapt it for their usage.

**Comment by ajeetdsouza** [comment]
Are you caching zoxide's results in Redis? `hyperfine 'redis-cli PING'` seems to take roughly 4.0ms on my machine, which zoxide usually outperforms.

**Comment by NightMachinary** [comment]
[**@Ajeet D'Souza**](https://github.com/ajeetdsouza) commented on [Apr 15, 2021, 12:03 AM GMT+4:30](https://github.com/ajeetdsouza/zoxide/issues/182#issuecomment-819779254 "2021-04-14T19:33:30Z - Replied by Github Reply Comments"):
> Are you caching zoxide's results in Redis? `hyperfine 'redis-cli PING'` seems to take roughly 4.0ms on my machine, which zoxide usually outperforms.

I don't cache zoxide 😄. (It gets stale fast.) I cache the interactively chosen directory for each query. Basically, instead of relying on the scores to choose, I choose once for each query, and then this choice gets saved in redis:
![image](https://user-images.githubusercontent.com/36224762/114769302-4b9e3900-9d7f-11eb-9835-0a0f8ae97112.png)

As you see, the default choice for each query is still extremely good.

**Comment by ajeetdsouza** [comment]
I see. Why do you want zoxide to show directories that no longer exist, though? That seems like it would still be useful here, and it takes less than a millisecond to check.

**Comment by NightMachinary** [comment]
[**@ajeetdsouza**](https://github.com/ajeetdsouza) commented on [Apr 15, 2021, 11:37 PM GMT+4:30](https://github.com/ajeetdsouza/zoxide/issues/182#issuecomment-820666237 "2021-04-15T19:07:20Z - Replied by Github Reply Comments"):
> I see. Why do you want zoxide to show directories that no longer exist, though? That seems like it would still be useful here, and it takes less than a millisecond to check.

I have no idea what it is that causes `zoxide query --list` to take a second or two every now and then, so I just suggested the easiest way, which is to turn off all the bells and whistles. Perhaps the dir checking is slow when external HDDs are present? 

Is there any sort of caching done on `zoxide query --list`? I can never reproduce its slowness deliberately, it just happens.

**Comment by ajeetdsouza** [comment]
Before printing a matched directory, zoxide first verifies that it actually exists on disk. This is to avoid accidentally choosing a deleted directory, so this operation can't be cached. If you cd into a lot of paths on the external disk, then zoxide would need to check all of them (therefore accessing the disk). It's still strange that you're experiencing such a dramatic slowdown, but only some of the time - perhaps when the external disk is under heavy load?

Could you run this with the external disk connected?

```sh
# How many entries are there in total?
zoxide query -ls | wc -l

# How many of them are on the disk? (assuming it is mounted at /mnt/disk)
zoxide query -ls /mnt/disk / | wc -l
```

I've drafted a PR to improve query performance (https://github.com/ajeetdsouza/zoxide/pull/185). It still checks if the directory exists before printing, but it should be a lot faster (especially for empty queries). Could you try it and tell me if it works?

```sh
cargo install --path=.

# On Linux, musl tends to be faster:
cargo install --path=. --target=x86_64-unknown-linux-musl
```

**Comment by NightMachinary** [comment]
@ajeetdsouza Here is the info:
```
❯ zoxide query -ls | rg Volumes | wc -l                                                                    
      12

❯ zoxide query -ls | wc -l                                                                               
     142
```

The external disk is an HDD. I'll try that PR out, but since the delays are nondeterministic, we'll have to wait and see for some time. Thanks! \(ᵔᵕᵔ)/

**Comment by NightMachinary** [comment]
@ajeetdsouza The update has either not changed anything, or it has made it worse, unfortunately.

**Comment by ajeetdsouza** [comment]
Since you have a fairly small number of directories, this is definitely an I/O problem. zoxide calls `stat()` before printing matches to check that the directory still exists.

I do agree that zoxide should have a way to show _everything_ in the database, regardless of whether it still exists or not. I've created a PR with a `zoxide query --all` flag. Naturally, this is a lot faster than regular queries, but you will also see deleted directories in your result, which can be quite annoying.

**Comment by ajeetdsouza** [comment]
Hey @NightMachinary, were you able to test out the `--all` flag?

Also, I just merged https://github.com/ajeetdsouza/zoxide/pull/213, which should give you a significant performance boost if you have a lot of deleted entries that are still in zoxide.

**Comment by MahouShoujoMivutilde** [comment]
Hi, i had a similar issue, and just wanted to let you know that `--all` is really helpful, thanks for that.

I have a pc with 1 ssd for system, smaller files, etc + few large hdd for movies and other large things.

Since some of portion of my jump list is on hdd, check for existence is quite slow, especially if it's on NAS / disk turned off for power saving.

So what happens when i use `zoxide query -i` is that i get like half of the list pretty fast, and the other part in next ~3 seconds.

With `--all` it's instant. 

(And missing directories with low score can be just periodically deleted with `zoxide remove`.)

**Comment by ajeetdsouza** [comment]
Hey @MahouShoujoMivutilde, thanks for the feedback! I'll close this issue then. Btw, if you don't mind losing autojump on your NAS, you can set `_ZO_EXCLUDE_DIRS` to ignore your NAS.

**Comment by MahouShoujoMivutilde** [comment]
No, i'd rather keep them ;)

Now that i thought about it, i should probably setup [lvm cache](https://wiki.archlinux.org/title/LVM#Cache), that might actually give me the best of both ways.

**Comment by YodaEmbedding** [comment]
Is there a way to manually trim away directories that no longer exist from the database? (e.g. `zoxide remove --missing`). That way, `zoxide query --all` can be used to bypass slow random `stat` I/O, but the database may be cleaned up every once in a while manually.

I do something similar with my [`frece`](https://github.com/YodaEmbedding/frece) project -- directories can be trimmed away on a database "refresh", but are otherwise kept for fast querying.

**Comment by MahouShoujoMivutilde** [comment]
Like this, but it will trim not mounted too.

```sh
zoxide query --all -l | while read -r dir; do
    if [ ! -d "$dir" ]; then 
        echo "$dir"
        zoxide remove "$dir" 
    fi
done

```

**Comment by ajeetdsouza** [comment]
What I was saying is, zoxide automatically does exactly this once the entry becomes 90 days old. Is there any reason you want to do it immediately?

Most of the time, invalid entries don't really end up slowing down zoxide, because 1. zoxide only checks directories that match the search query, and 2. zoxide checks them in order of score, and deleted directories don't usually have a very score.
