### ISSUE TITLE
Ignore `$HOME` in the hook by default

### ISSUE THREAD

**Issue by kidonng** [ajeetdsouza/zoxide#189]
Most of the time, `$HOME` scores the highest among all the directories, for obvious reasons.

I'm not sure about other shells, but zsh and fish treats a bare `cd` as `cd ~`, and it seems zoxide inherits this behavior. If one wants to go home, they can simply use `cd` or `z`, which makes `$HOME` useless in the database.

I propose to ignore `$HOME` in the hook by default. Well, this can already be achieved with `$_ZO_EXCLUDE_DIRS`, but I consider it a sensible default that should require no extra configuration.

Some other directories such as `$TMPDIR` (`/tmp`) could be excluded as well.

**Comment by ajeetdsouza** [comment]
I've created a PR for `_ZO_EXCLUDE_DIRS` to default to `"$HOME"`. The only place where this could possibly be a problem is if someone attempts to share the same database across multiple users, and wants to cd between individual home directories. Ideally, different users would use different databases, so this should not be a problem.

I don't think `/tmp` should be default, though - I myself often use `z tmp`.

**Comment by kidonng** [comment]
> Ideally, different users would use different databases, so this should not be a problem.

That's exactly my thoughts.
Plus you can still use `~<username>`, for example if you need to go to `tom`'s home, just `cd ~tom`.

> I don't think `/tmp` should be default, though - I myself often use `z tmp`.

Yeah I figured out the directories don't survive a boot and will be automatically cleaned by zoxide.
BTW, auto clean really makes zoxide different from similar projects ♥️

**Comment by ajeetdsouza** [comment]
Actually, zoxide used to have a lazy cleaning algorithm that did this.

`zoxide query keywords` works by extracting the subset of directories matching `keywords`. Then, it sorts them in descending order of score. After this, it iterates through the list of paths and prints the first result that is currently a directory.

When lazy cleaning was enabled, if zoxide encountered a path while iterating over a query, it would immediately remove it from the database. So, the easiest way to remove deleted paths from the database would be `zoxide query -l` since it forces zoxide to read the _entire_ database.

Unfortunately, that feature had to be removed, because people wanted to use zoxide with external HDDs. In practice, however, deleted paths don't really cause too much of a slowdown. The frecency algorithm puts them last in the result set, so we rarely check those directories.

**Comment by kidonng** [comment]
Thanks for the explanation!

**Comment by kidonng** [comment]
One more question, does this mean zoxide only has one auto cleaning mechanism: aging?

**Comment by ajeetdsouza** [comment]
Currently, yes. Making it less aggressive is a good idea, though. Perhaps we could lazily delete any path that is inaccessible _and_ hasn't been accessed in the last 90 days, for example.

**Comment by ajeetdsouza** [comment]
@kidonng I've created a PR to do this: https://github.com/ajeetdsouza/zoxide/pull/213
