### ISSUE TITLE
glibc binary releases are no longer built

### ISSUE THREAD

**Issue by SanchithHegde** [ajeetdsouza/zoxide#201]
I just checked the release GitHub workflow file and it looks like glibc binaries are no longer built since fec064a1ef0517b7107730581c47dd132f09de45. This affects the following targets:

- `x86_64-unknown-linux-gnu`
- `aarch64-unknown-linux-gnu`
- `armv7-unknown-linux-gnueabihf`

Was this change intentional?

**Comment by ajeetdsouza** [comment]
Hey, I've removed the glibc binaries in favour of the musl ones for two reasons:
- the musl binaries tend to have faster startup times (translating to less latency in your shell)
- they are more portable, since they aren't tied down to any particular version of glibc

Is there any reason you wanted the glibc binaries?

**Comment by SanchithHegde** [comment]
Well, I'd just prefer to have glibc binaries since I use a distro which uses glibc (Arch) and wouldn't want any surprises with musl binaries. I'm not that knowledgeable about glibc vs. musl, so I'm not sure if I'd face any problems either.  

If the change was intentional, then that's fine. I'll switch to building from source, and I'll close this issue.
