### ISSUE TITLE
rm 'cd dir' if dir exists behavior

### ISSUE THREAD

**Issue by XyLyXyRR** [ajeetdsouza/zoxide#214]
I'm was confused because this.

- open a terminal
- type 'z bin' # I'm thinking I'll go `~/.cargo/bin/` but it jump into `~/bin`

I was so confused for 30 mins, because it's works normal before today.

I tried to rm zoxide.db and import from z again, and `zoxide remove -i bin` a few time. But nothing changes.

Finally, I noticed there is a 'bin' dir in my home, might be termux did this, cause a link file 'termux-file-editor' is in there. And it's back to normal after I removed this dir.

Since we can easily `cd bin` or just `bin` in some shells to jump into dir, I want `z bin` rm `cd dir` bahevior.

Thank you.

**Comment by ajeetdsouza** [comment]
Hey @XyLyXyRR,

This is expected behaviour. `z` always works as a cd command first, and falls back to querying from the database. The idea is for `z` to completely replace your `cd` command, so that you don't have to decide between the two every time you change your directory.

That said, if you really want to change this behaviour, you could easily write a simple `z` function. Assuming you're on zsh:

```zsh
function z() { cd "$(zoxide query --exclude "$(pwd)" -- "$@")" }
```

**Comment by XyLyXyRR** [comment]
Thanks for your reply.

I just tried that. I decide to overwrite '__zoxide_z' function manully.
