### ISSUE TITLE
Add support for skim

### ISSUE THREAD

**Issue by pickfire** [ajeetdsouza/zoxide#228]
I am saw that there were issues in the past #3, #31 and #78. Although skim is slower but you can't notice the difference unless you have lots of files. But I only have skim installed locally, I didn't have fzf installed because I think skim works well enough. All the other issues are closed and I think it's long enough to open it again.

Can we add support for skim as a fallback in case fzf binary is not found? https://github.com/ajeetdsouza/zoxide/blob/main/src/fzf.rs skim is a drop-in replacement so we can just fallback to skim binary with the exact same options if fzf is not found.

**Comment by ajeetdsouza** [comment]
Hey @pickfire, if skim is a drop-in replacement, you can create a symlink to it like so:

```sh
ln -s "$(which skim)" ~/.local/bin/fzf
```

That way, any tool requiring fzf would work out of the box for you.

**Comment by pickfire** [comment]
The binary is `sk` but usually from what I see the original skim developer duplicates it to make use of sk rather than soft link. It would work but I feel like that's a hack.

**Comment by ajeetdsouza** [comment]
@pickfire it's fairly common behaviour to alias / symlink a drop-in utility to replace the old one, afaik.

Also, the `$_ZO_FZF_OPTS` environment variable in zoxide works by setting `$FZF_DEFAULT_OPTS`. This doesn't work on skim.

**Comment by pickfire** [comment]
IIRC skim replaces those environment variables with `SK` rather than `FZF`. But I don't set any of those options.

**Comment by ajeetdsouza** [comment]
@pickfire I understand that you don't set `_ZO_FZF_OPTS`, but it still winds up becoming a half-baked solution for everybody else. However, the point of zoxide is for it to be hackable, and there are two very easy ways to go about this:

- Create `~/.local/bin/fzf`. This ensures that any tool expecting `fzf` will automagically switch over to `skim`. It's fairly common to use symlinks or aliases for this too.
```bash
#!/usr/bin/env sh
SK_DEFAULT_OPTS="$FZF_DEFAULT_OPTS" sk "$@"
```

- Writing your own `zi` is quite easy:
```bash
function __zoxide_zi() {
    result="$(zoxide query -ls -- "$@" | sk)" && cd "$result"
}
```

**Comment by ajeetdsouza** [comment]
It's not half-baked, it's simply a sane default. The builtin `zi` function uses `fzf` because it is the best in terms of speed, compatibility, and popularity. Even if you use `skim` otherwise, it's not very hard to install `fzf` as well - most package managers have it, and it's a 3 MB binary.

The `zoxide` binary has a variety of thoroughly documented commands _because_ every user has different requirements -- you are _encouraged_ to write your own creative functions as needed. As I said, writing a basic `zi` shell function takes 3 lines of code, so I don't see why you want `skim` support to be embedded in the binary.

In fact, I myself would have preferred to put the `fzf` logic into the shell code rather than the `zoxide` binary -- the only reason I haven't done so is because I'd have to repeat that logic 8 times (`zoxide` supports 8 shells). The trouble with adding more fuzzy finders is that `skim` is hardly the only one:

- [`fzf`](https://github.com/junegunn/fzf)
- [`peco`](https://github.com/peco/peco)
- [`selecta`](https://github.com/garybernhardt/selecta)
- [`pick`](https://github.com/mptre/pick)
- [`pmenu`](https://github.com/sgtpep/pmenu)
- [`ipt`](https://github.com/ruyadorno/ipt)

I think a far more scalable alternative is to let people write their own custom functions for the behavior they desire, so I'm closing this issue.

**Comment by cpick** [comment]
@ajeetdsouza 
>     * Writing your own `zi` is quite easy:
> 
> 
> ```shell
> function __zoxide_zi() {
>     result="$(zoxide query -ls -- "$@" | sk)" && cd "$result"
> }
> ```

Due to [this `skim` bug](https://github.com/lotabout/skim/issues/457) and the need to skip the score when passing the directory to `cd`, I've found I get good results with:
```shell
function __zoxide_zi() {
    \builtin local result
    result="$( \
        zoxide query -ls -- "$@" \
        | sk \
            --delimiter='[^\t\n ][\t\n ]+' \
            -n2.. \
            --no-sort \
            --keep-right \
            --height='40%' \
            --layout='reverse' \
            --exit-0 \
            --select-1 \
            --bind='ctrl-z:ignore' \
            --preview='\command -p ls -F --color=always {2..}' \
        ;
    )" \
        && __zoxide_cd "${result:5}"
}
```

**Comment by avarun42** [comment]
Is it possible to consider reopening this now that `skim` is officially faster than `fzf`? (See [here](https://github.com/skim-rs/skim/releases/tag/v4.0.0)). I think `skim` has gotten enough momentum at this point and has the advantage of being rust-native that it deserves native support. If not that, at least a guide in the README that explains how to use it with zoxide.

**Comment by DeltaCream** [comment]
> Is it possible to consider reopening this now that `skim` is officially faster than `fzf`? (See [here](https://github.com/skim-rs/skim/releases/tag/v4.0.0)). I think `skim` has gotten enough momentum at this point and has the advantage of being rust-native that it deserves native support. If not that, at least a guide in the README that explains how to use it with zoxide.

I also concur.

If necessary, I can share later what I have tried by documenting what happens with stripping out zoxide functions that use fzf and replacing it with skim, to show that while it is possible for the user to replace the fzf integration, it is a lot of trouble considering that skim might be the better or faster choice for fuzzy matching.

**Comment by Sympatron** [comment]
As of now skim is not cross platform. So using it would remove some platform support for zoxide which I think would be unacceptable.
They [seem to be working on it](https://github.com/skim-rs/skim/pull/1010) though, so it might be feasible soon.

**Comment by DeltaCream** [comment]
> As of now skim is not cross platform. So using it would remove some platform support for zoxide which I think would be unacceptable.
> They [seem to be working on it](https://github.com/skim-rs/skim/pull/1010) though, so it might be feasible soon.

Interesting observation, and understandable honestly.

If that's the case, it would be warranted to wait at least for skim Windows support before moving forward with this issue.

For the meantime I'm working on sending at least some of the alternative fish (as I don't use zsh or bash currently) functions which use skim instead of fzf, as present in zoxide's documentation in this issue here.

If there's a more appropriate place to send these instead of this issue, I would be happy to comply.

**Comment by DeltaCream** [comment]
> As of now skim is not cross platform. So using it would remove some platform support for zoxide which I think would be unacceptable. They [seem to be working on it](https://github.com/skim-rs/skim/pull/1010) though, so it might be feasible soon.

As of [this release](https://github.com/skim-rs/skim/releases/tag/v5.0.0), skim now has Windows support, though there is still work to be done.

How feasible is it going to be now?
