### ISSUE TITLE
cd between the historical directories of current window/pane/tab

### ISSUE THREAD

**Issue by c02y** [ajeetdsouza/zoxide#242]
For instance, I have multiple window/pane/tab of the same terminal opened at the same time, in just one single window/panes/tab, I cd into multiple directories, how can I switch to another directory from the current window/pane/tab history instead of the whole history across window/pane/tab. 

Currently, the only command I can use is `z -` which is cd between previous and current directories, but I don't remember the exact or even a keyword of the directory of the older history for the window/pane/tab.

If this is not implemented, you can consider this is a new feature request.

**Comment by ajeetdsouza** [comment]
Hey, which shell are you using?

**Comment by c02y** [comment]
fish-shell

**Comment by ajeetdsouza** [comment]
The thing is that requests like these are quite specific in nature. There was an [feature request](https://github.com/ajeetdsouza/zoxide/issues/122) a while back for something similar, but that user wanted global history rather than shell-specific history, and wanted to access directories by order of recency.

Fortunately, zoxide tends to be quite scriptable, since the actual shell logic tends to be quite minimal. Try running `zoxide init fish` and see the code for `__zoxide_z` (which is your `z` command). If you replaced all the `cd` commands with `pushd` and replaced `cd -` with `popd`, would that solve your use case?

**Comment by c02y** [comment]
I came from z.lua a long time ago, I remembered that z.lua has this option for this kind of purpose, just like the issue page you mentioned, it is a similar request.

If I changed `__zoxide_z` as you suggested, it affects the other normal command too, what I need is more like an option, without this option `z` command remains its current strategy.

You can create a unique ID for every window/tab/pane, when using this option, get all entris for the ID of the current window/tab/pane. I think this design is cross-shells, without using this option, ignore all the IDs.

**Comment by ajeetdsouza** [comment]
I think I'm still a little confused about the feature you're requesting. Do you think you could describe it with an example?

**Comment by c02y** [comment]
>For instance, I have multiple window/pane/tab of the same terminal opened at the same time, in just one single window/panes/tab, I cd into multiple directories, how can I switch to another directory from the current window/pane/tab history instead of the whole history across window/pane/tab.

The current db contains all dirs(ListA) for all open window/pane/tab and sessions in the feature, the request is a local history(ListB) for the current window/pane/tab, `z` command will search/list all dirs in ListA, `z + an option` is needed to search/list the ListB.

For example, `/path/a`, `/path/b`, `/path/c`, `/path/d` are saved for all open window/pane/tab and sessions in the feature, if I only cd `/path/a`, `/path/c` after I created the current one window/tab/pane, `z + an option` will seach/list only `/path/a`, `/path/c`. very open window/tab/pane has a specific local history.

**Comment by ajeetdsouza** [comment]
I don't think a feature like this justifies the overhead and complexity of maintaining a new file per shell. However, most of the functionality you describe is already present in fish:

```fish
cd (string collect $dirprev | fzf --tac)
```

**Comment by c02y** [comment]
A new file is unnecessary, just add an ID tag of every currently open window/pane/tab for its historical entries.

I didn't analyze the code, maybe it's too complicated to implement.

Anyway

> cd (string collect $dirprev | fzf --tac)

is a nice trick, this is exactly what I need.

**Comment by ajeetdsouza** [comment]
It's not complicated as such, it's just that you have to keep track of more metadata to know when to delete tags that have expired. On the other hand, it's far easier to track things like this with a shell variable like `$dirprev`, since it doesn't need to be persistent.

I'm glad this solution is working for you, do let me know if you have further questions.

**Comment by c02y** [comment]
I found that `Alt-Left/Right` in fish-shell will get a similar function, it just loops the historical directories one by one.

And there is a bug of `cd (string collect $dirprev | fzf --tac)`, if I `C-c` or `Escape` from the `fzf` list, it will always cd into `~/`, so this is an improved version if anyone needs it:
```
function zb -d 'zb go back to the history of current window/tab/pane'
    set dir (string collect $dirprev | fzf --tac)
    if test $dir
        z $dir
    end
end
```
