### ISSUE TITLE
[Enhancement] Select directory on multiple matching results

### ISSUE THREAD

**Issue by HenrikStanley** [ajeetdsouza/zoxide#246]
Currently zoxide will select a folder matching my query and take the first results that matches.
However if you have multiple folders that could match, you do not get the chance to select that folder instead.

Example:
Lets say we have these two folders:
/home/projects/project1/terraform
/home/projects/project2/terraform

if I have visted both folders previously and I run:
z terraform

I will be navigated into the first folder.

My suggestion is that in cases with multiple matches, an fzf like file promt will show which folders matched and allow the user to select which folder to jump to.

To not break current workflows it could be an option / flag you set.

**Comment by ajeetdsouza** [comment]
Hey @HenrikStanley,

`z` commands are usually expected to be very short. For example, you're not expected to type out the whole directory name -- for a directory named `~/foo/terraform`, one would usually use `z ter` and let zoxide figure it out. In your case, it's easy enough to distinguish between the two -- use `z 1 ter` for the first directory, and `z 2 ter` for the second one.

In a general sense, since queries are usually very small, there is more than one result in almost all zoxide queries, which is why we use a ranking algorithm to find the most probable match. If a user had to actually choose the directory from fzf every time, `cd` would be faster to use than `z`. Also, since `z` commands exclude the current directory, if `z` takes you to the wrong directory, you can just run it again to go to the second best match.

However, if you really wanted the functionality you're talking about, you can do this:

- `export _ZO_FZF_OPTS='--select-1'`, this ensures that `zi` acts immediately if there's only one result.
- Initialize zoxide with `--no-alias`, this prevents `z` and `zi` from being defined.
- Create an `alias z=__zoxide_zi` to enable interactive selection.
