### ISSUE TITLE
[feature request] Configurable expiration policy

### ISSUE THREAD

**Issue by yshui** [ajeetdsouza/zoxide#292]
The aging algorithm used by most of the `z` implementations aren't actually that good. At least it probably wouldn't suit everybody's need.

To illustrate the problem, suppose the max age is 1000, and suppose there is a directory that has been used a lot in the past, so let's say its rank is 100. But that could be from 900 commands ago. If these 900 commands each use a different directory, then all of them could be expired after the user inputs one more command, leaving only the old entry behind.

Some users might prefer this behavior, but it would be nice to have this configurable, with alternatives like the straightforward LRU policy.

**Comment by ajeetdsouza** [comment]
zoxide does actually give preference to newly accessed directories:

| Last access time     | Frecency    |
| -------------------- | ----------- |
| Within the last hour | `score * 4` |
| Within the last day  | `score * 2` |
| Within the last week | `score / 2` |
| Otherwise            | `score / 4` |

This means that a directory that was last accessed in the last hour would have a *16x* boost in its score compared to something accessed a week ago. Could you elaborate more on why this isn't working for you?

**Comment by yshui** [comment]
My understanding is that this only changes sorting, not when entries are removed from database?

**Comment by ajeetdsouza** [comment]
Why do you want to remove directories from the database?

**Comment by yshui** [comment]
I am not sure what you mean. zoxide is removing directories using the aging algorithm, IIUC.

> Thereafter, if the new score of any directory falls below 1, we remove it from the database.

**Comment by ajeetdsouza** [comment]
You're saying the current deletion algorithm is not working well for you. I'm trying to understand why it isn't working well. Ideally, deletion of directories from the database should not be something that a user has to worry about.

**Comment by yshui** [comment]
In my top most comment, I did try to explain a scenario why the current algorithm is not working well, if it was no clear I can try again.

**Comment by ajeetdsouza** [comment]
A clarification with a specific example of something that wouldn't work with the current algorithm would be nice.

As I explained, a directory that has not been accessed for a long time has a reduced score, and a directory that has been accessed recently has a boosted score. So the boosted directory would always show up as a match before the other one.

I don't see why _deleting_ the older directory (instead of reducing its score) would produce different results here.

**Comment by ajeetdsouza** [comment]
If the aging algorithm were changed to consider the boosted score instead, would that fix your issue?

**Comment by yshui** [comment]
No, as I explained:

> And it still won't work for things that are not boosted, e.g. directory that was accessed a ton a month ago vs directory I accessed a couple of times yesterday.

**Comment by ajeetdsouza** [comment]
> And it still won't work for things that are not boosted, e.g. directory that was accessed a ton a month ago vs directory I accessed a couple of times yesterday.

Something you accessed yesterday would be 8x as important as something you accessed last month. If you accessed something more than 8x as much last month, chances are that it was an important directory anyway. If you really want to remove it you can always run `zoxide remove` on that directory.

> Yes, you can probably make the boosting factors configurable, but if you do that you might as well add a couple different algorithms.

Firstly, you still haven't made it clear why deletion would have performed better than a boosting algorithm (maybe with different parameters) here. Secondly, I'm not really a fan of the idea of adding "a couple different algorithms" for one user. If you have suggestions to improve (not replace) the default algorithm, and if you can provide some intuition as to why it would perform better, I'd be happy to hear them.
