### ISSUE TITLE
Doesn't go to the right directory

### ISSUE THREAD

**Issue by Milo123459** [ajeetdsouza/zoxide#295]
Hey! I have these 2 folders registered into Zoxide: `rust` and `rust-analyzer`. When I type `z rust` it takes me to rust-analyzer, when it should take me to the rust directory.

Thanks!

**Comment by ajeetdsouza** [comment]
This is happening because `rust-analyzer` has a higher score than `rust`. You can artificially change the score by removing the `rust-analyzer` directory (using `zoxide remove`) or by inflating the score of `rust` (using `zoxide add`).

This issue was already reported in https://github.com/ajeetdsouza/zoxide/issues/247, so I'll close this in favor of that. Unfortunately, as I noted in my last comment, there's no one-size-fits-all solution to this (yet). rupa/z has some logic that attempts to solve this, but the author admits in one of the issues that the approach may have been suboptimal.

Some more query improvements were suggested in https://github.com/ajeetdsouza/zoxide/issues/260. I'd love to hear your thoughts there as well.

**Comment by marcelarie** [comment]
What I do it's give one more letter that can make the difference between both matches:

For **~/home/rust**:
`z rust`
For **~/home/clones/rust**:
`z c rust`
