### ISSUE TITLE
Document that webinstall.dev/zoxide installs more than zoxide

### ISSUE THREAD

**Issue by loganlinn** [ajeetdsouza/zoxide#318]
Reviewing the script returned from `curl -sS https://webinstall.dev/zoxide` ([gist](https://gist.github.com/loganlinn/e2460478a77262e63a374384139dec38)), I was surprised to see that it installs additional tools (`webi`, `pathman`, `envman`, more?) to the environment that don't get cleaned up _and_ make unannounced changes to `~/.bashrc`, `~/.zshrc`, etc.

I understand these sorts of installers are not for everyone and the benefits the webinstall project provides to OSS maintainers, but I have a strong feeling this sort of low-visibility "tool bundling" is unexpected behavior to most.

**Comment by ajeetdsouza** [comment]
I agree with you, I'm not a fan of how the installs happen either. I've been waiting since the maintainer of `webi` says he's open to fixing this, but if that doesn't happen we may have to roll our own installer instead.

**Comment by nonissue** [comment]
Wow, this is a huge issue imo. MULTIPLE files are installed without any kind of notification:

```
~/.local/bin/webi
~/.local/bin/pathman
~/.local/opt/pathman-*
```

Additionally, a bunch of files are _**SILENTLY**_ modified:

```
~/.bashrc
~/.profile
~/.config/fish/config.fish
~/.config/envman/PATH.env
```

I would *never* have used the `webinstall.dev` had I known this in advance, and yes, I should have checked more thoroughly, but I'm shocked that both the zoxide README and the actual `webi` shell instructions make no mention of the numerous changes made.

**Comment by ajeetdsouza** [comment]
Hey, zoxide now ships its own installer once again. Sorry this took so long!

**Comment by nonissue** [comment]
Thank you ☺️

**Comment by coolaj86** [comment]
Thanks to updates in PowerShell and my better understanding of bash, Webi no longer depends on `pathman`. \
(it never did install `envman`, as it never existed - that's just the folder for machine-readable ENVs)

The `webi` command still installs itself because of the bootstrap process (`curl` doesn't include a standard User-Agent string with os and arch info).

There's also now a `Files` section in each installer that accounts for any non-standard changes.

Webi is for an audience of people who are typically less familiar with the nuances of PATH updates, but I'm open to ideas on how to better communicate that still. I'll have to double check that there's output when `~/.bashrc` and friends are modified the first time.
