### ISSUE TITLE
Why have to press space before completion?

### ISSUE THREAD

**Issue by PatrickF1** [ajeetdsouza/zoxide#325]
For me, it's unintuitive that if I want to get completions for a directory starting with d that I have to type `z d<SPACE><TAB>`. Why not just `z d<TAB>`>? I noticed that the latter is how https://github.com/skywind3000/z.lua#completion works and so it's definitely technically feasible.

**Comment by PatrickF1** [comment]
Oh I see...is it because z is used as a regular cd command? That's a bit different from other smart cd tools. I guess the advantage is that it is one char shorter to type. But then I as a user might conflate whether I am trying to use z's special features with regular cd features.

**Comment by ajeetdsouza** [comment]
> I guess the advantage is that it is one char shorter to type.

IMHO, the biggest advantage is that it becomes a lot easier to commit `z` to muscle memory when you don't have to decide between typing cd vs. z every time you want to change directories. In fact, I've seen a bunch of users actually replace their cd command entirely:

```sh
zoxide init --cmd cd <shell>
```

---

Secondly, zoxide is well integrated with [fzf](https://github.com/junegunn/fzf), and uses it for completions. fzf is an extremely versatile tool, and the repository includes [completion scripts](https://github.com/junegunn/fzf/tree/master/shell) that allow it to autocomplete regular commands like `git`, etc.

The way they do it is by relying on a specific trigger (by default, `**`). This means that if you type `**<tab>`, it opens up fzf completions. I had initially integrated `**<tab>` based completions into zoxide as well for uniformity, but I soon realized that it was very tedious to type, and I never ended up using the feature for that reason.

While looking for a trigger that was easier to type, I realized that `z` can just use <kbd>space</kbd>, because cd only takes one argument. If you hit <kbd>space</kbd>, that starts a second argument, so zoxide understands that you want to "jump" directories, and shows interactive completions.

**Comment by PatrickF1** [comment]
> IMHO, the biggest advantage is that it becomes a lot easier to commit z to muscle memory when you don't have to decide between typing cd vs. z every time you want to change directories.

Interesting. I never had an issue with committing z to muscle memory. I think it's actually a positive thing to separate them. It simplifies the mental model and for you as the developer, it would simplify the code and having to explain the feature. Also, having a clean separation allows greater freedom to do what you want with z, e.g. tab to trigger completions without a space. But I understand this feature is already baked in and making this change would break half zoxide user's workflows so I won't belabor this. However, I will say that I applaud you for making a bold powerful move introducing a new paradigm 👏

> While looking for a trigger that was easier to type, I realized that z can just use space, because cd only takes one argument.

I see. So from a technical standpoint, you implemented interactive completions by integrating with fzf by using <space><tab> as the trigger. I'm very curious about this. Could you link to that code please?

Btw, I'm actually a fellow fzf-related plugin author myself. Check out my repo! It's not as big as yours and it seems I have a lot to learn from you! https://github.com/PatrickF1/fzf.fish

**Comment by ajeetdsouza** [comment]
> So from a technical standpoint, you implemented interactive completions by integrating with fzf by using `<space>` as the trigger.

Not exactly. I created a regular completion function for `z` that only launches fzf when the last argument is empty (which means the user has hit `<space><tab>`. The code is [here](https://github.com/ajeetdsouza/zoxide/blob/main/templates/fish.txt#L76), it's written in a templating language called [Askama](https://github.com/djc/askama), but it should be reasonably straightforward to understand. I'm not a Fish user myself, so I'd love to hear any thoughts you have!

> Btw, I'm actually a fellow fzf-related plugin author myself.

That's a fantastic plugin! Is there a way to just entirely replace the default completions? Like `git status<tab>` should directly show `fzf` completions? Also, I like your GIFs! What did you use to record them?

**Comment by PatrickF1** [comment]
> The code is here, it's written in a templating language called Askama, but it should be reasonably straightforward to understand. I'm not a Fish user myself, so I'd love to hear any thoughts you have!

That's very idiomatic fish code :)! My only minor suggestion is to use the long form options for commandline (the fish devs went to great pains to make long form options for all of the standard library so that we can make our scripts more readable).

> That's a fantastic plugin! Is there a way to just entirely replace the default completions? Like git status<tab> should directly show fzf completions? 

That's technically feasible but right now I'm focusing on key-binding-driven-insertion-of-entities.

> Also, I like your GIFs! What did you use to record them?

Thank you! Boy do I have some documentation for you! Check out https://github.com/PatrickF1/fzf.fish/pull/47.

**Comment by ajeetdsouza** [comment]
> My only minor suggestion is to use the long form options for commandline

I agree, long form is more readable! I've changed it here: https://github.com/ajeetdsouza/zoxide/commit/027d259c894073365b737b9ddbf6c2d45d37a0f1

> Thank you! Boy do I have some documentation for you! Check out PatrickF1/fzf.fish#47.

This is fantastic, thanks! I'm using asciinema too, but because I wanted Nerd Fonts I wasn't able to convert it to a GIF. I'll probably try it again, it seems like it's worth the effort!
