### ISSUE TITLE
Unable to get interactive completions on zsh

### ISSUE THREAD

**Issue by indigoviolet** [ajeetdsouza/zoxide#348]
I have the exact same problem as https://github.com/ajeetdsouza/zoxide/issues/336, but I have verified that I am using zoxide 0.8.0.

`zi` shows a sorted list of directories as expected, but `z foo<tab>` only loads completions from the current directory. 

I have `autoload -Uz compinit; compinit -i` etc.

Any suggestions? What debugging information would be useful?

**Comment by indigoviolet** [comment]
@RayZ0rr thanks, that does work, and I realize now that the documentation mentions the `<space>`. 

@ajeetdsouza Why did you choose/need to have the `<space>` before the `<tab>`? That feels really unusual compared to how I would expect completions to behave.

**Comment by ajeetdsouza** [comment]
`z` doubles up as both a cd and a jump command. Simply putting a `<Tab>` will show you `cd` completions, but a `<Space><Tab>` will open fzf with all the matches from zoxide.

The other point is that I don't expect users to require `<Space><Tab>` too often. Using the interactive selector takes much longer than just typing the `z` command with enough context. It's meant to be used in cases where the algorithm cannot differentiate between directories, eg. `/home/foo` and `/home/foobar` with a query of `"foo" `.

**Comment by ajeetdsouza** [comment]
> When you realize the wrong directory has been chosen, you will most likely just add context

To clarify the example: if you have two directories `/home/foo` (score 10) and `/home/foobar` (score 20), then `z foo` will take you to `/home/foobar`. There is no way to tell that the user wanted `/home/foo`, and this kind of problem is common across all the autojumpers that I've tried.

So if you're not sure where `z` will take you, you can use `<Space><Tab>` to find out. I'm hoping that this is a rare occurrence, because `z` is intended to be predictable by design.

> If `<Tab>` were to complete the target, choosing the top hit as the result by default

I tried using native completions instead of fzf as well (which would have done what you're describing), but it doesn't work very well when directory names are long or if there are too many results.

> I'm suggesting making it `z foo<tab><return>`

The problem lies in distinguishing whether the user wants to do a `cd` or a jump. Currently `<Tab>` is for `cd`, `<Space><Tab>` is for a jump.
