### ISSUE TITLE
unable to use autocompletion with z 

### ISSUE THREAD

**Issue by SamDc73** [ajeetdsouza/zoxide#384]
the auto completeion is invoked form the cd command not form the z database/directories 

for example when i'm on the home directory `z tab `should show me directories from the zioxide database, but instead it is showing me the home directories .

I'm using zsh on fedora 35:
`zsh 5.8.1 (x86_64-redhat-linux-gnu)`
`zoxide v0.8.0`
`fzf 0.29.0 (Fedora)`

my zsh plugins :
```
fzf-tab
zsh-syntax-highlighting
zsh-history-substring-search.plugin
sudo
dirhistory
fzf-marks.plugin
cheat
colored-man-pages.plugin
qoutes
fancy-ctrl-z
```

**Comment by ajeetdsouza** [comment]
To clarify -- are you loading zoxide at the _end_ of your .zshrc file? And are you calling compinit before that?

The following two lines should be at the end of your `.zshrc`:

```zsh
autoload -Uz compinit && compinit
eval "$(zoxide init zsh)"
```

**Comment by SamDc73** [comment]
> To clarify -- are you loading zoxide at the _end_ of your .zshrc file? And are you calling compinit before that?
> 
> The following two lines should be at the end of your `.zshrc`:
> 
> ```shell
> autoload -Uz compinit && compinit
> eval "$(zoxide init zsh)"
> ```

i tried what you said with no luck :(

**Comment by eigengrau** [comment]
I notice the same symptoms (Zoxide’s tab completion in Zsh is no longer working) after upgrading Zoxide from 0.7.9 to 0.8.1.

**Comment by gennaro-tedesco** [comment]
I am seeing the same problem: `z <Tab>` behaves like `cd <Tab>`, counterintuitively, rather than outputting the list of `zoxide` matches (namely the most navigated directories, more or less).

**Comment by ajeetdsouza** [comment]
That's because `z` also functions as a `cd` command. @SamDc73 I'm just reading your issue again and it appears to be the same thing, so I'm just clarifying this here:

- `z <tab>` should show `cd` completions.
- `z foo<tab>` should also show `cd` completions.
- `z foo<space><tab>` should show zoxide's completions.

The reason the completion system works this way is so that you can use `z` to enter local directories as well as directories anywhere on your filesystem. The [README](https://github.com/ajeetdsouza/zoxide#getting-started) contains a GIF of this.

**Comment by gennaro-tedesco** [comment]
Thank you for clarifying: you are right, it makes sense. So the actual `zoxide` completion is triggered with `z foo<space><tab>`:)!

**Comment by ajeetdsouza** [comment]
Closing since @SamDc73 seems to have had the same problem. Do let me know if this is not the case.
