### ISSUE TITLE
`zoxide remove -i` returns `unknown option: --keep-right`

### ISSUE THREAD

**Issue by T3sT3ro** [ajeetdsouza/zoxide#405]
version: `v0.8.1`
installed by: webi installer
command: `zoxide remove -i [PATH]`

expected result: prompt interactive removal [of matching paths]

actual:
> unknown option: --keep-right
> zoxide: fzf returned an error

**Comment by ajeetdsouza** [comment]
Hey, looks like your fzf is out of date. Upgrading it should fix this error.

**Comment by T3sT3ro** [comment]
> Hey, looks like your fzf is out of date. Upgrading it should fix this error.

`sudo apt update` returns no updates for the `fzf` package and `apt list fzf` returns:
> fzf/focal,now 0.20.0-1 amd64 [installed]

**Comment by T3sT3ro** [comment]
Updated fzf (reinstalled via `git clone` instead of `apt`) to most recent (0.30) version fixed it.

**Comment by igormcsouza** [comment]
It looks like this error is related to zoxide using newer features but my OS has an older version for fzf.. 

On the official documentation for fzf it asks to use 0.20.0 on ubuntu 20.04, so that's what apt installs on my machine! Not sure if I should force a newer version that.. since fzf can break and causes issues! Maybe zoxide can checkout what version of fzf to use or default to 0.20.0 which works on major distributions!
