### ISSUE TITLE
string match: Unknown option '--groups-only'

### ISSUE THREAD

**Issue by Fujiwara-Chika** [ajeetdsouza/zoxide#410]
![image](https://user-images.githubusercontent.com/44722787/176840964-865db821-1e63-4b17-a382-06ac753852cb.png)
Ubuntu 22.04 LTS on Windows 10
fish 3.3.1

**Comment by ajeetdsouza** [comment]
zoxide only supports Fish v3.4.0+. I've added that to the README to resolve future confusion.

**Comment by dpc** [comment]
This makes `zoxide` not work for fish users on the latest version of the latest release of the most popular Linux distro (Ubuntu). 

Downgrading with:

```
cargo install -f zoxide --version 0.7.9
```

fixed it for me (for other people that might be affected).

Please consider avoiding requirements on very recent versions of things in the future. I like `zoxide` in large part because it is blazingly fast and just reliably works. Small issues like this one just gets in a way. Anyway, thanks for your project - I don't want to sound negative.
