### ISSUE TITLE
FR: argv is a file (instead of a directory), open the directory the file is in

### ISSUE THREAD

**Issue by chrisgrieser** [ajeetdsouza/zoxide#431]
essentially this:

```zsh
function zFileOrDir () {
	if [[ -d "$1" ]] ; then
		z "$1"
	elif [[ -f  "$1" ]] ; then
		z "$(dirname "$1")"
	fi
}
```

a small change, but it would be a nice QoL change

**Comment by chrisgrieser** [comment]
Currently, I achieved the desired effect with this workaround. however, having is directly available would of course be preferable

```zsh
eval "$(zoxide init --no-cmd zsh)"
function z () {
	if [[ -d "$1" ]] ; then
		__zoxide_z "$1"
	elif [[ -f  "$1" ]] ; then
		__zoxide_z "$(dirname "$1")"
	fi
}
alias zi='__zoxide_zi'
```

**Comment by ajeetdsouza** [comment]
Hi, I don't think I understood what the purpose of this is. Why would you want something like this?

**Comment by chrisgrieser** [comment]
For example, I copy the path of a file from some app, for example a GUI file explorer. I switch to the terminal and want to go to the directory that contains that file.

Right now, it's "z, paste, remove filename, enter". With the suggested change, it would be "z, paste, enter". As I said, it's only a very minor quality-of-life change. However, since `z $file` currently does not do anything other than throwing an error, it would at least turn that case into something useful.

**Comment by ajeetdsouza** [comment]
Unfortunately, I don't see this as a common enough usecase to be added to the default implementation of `z`. That said, zoxide is built for customizability, which is why it exposes `__zoxide_z` to the user. Your custom `z` implementation seems like it would 
do the job.

I'm closing this issue for now, but I'm open to revisiting it if there is sufficient demand.
