### ISSUE TITLE
zoxide v0.3 - breaking changes

### ISSUE THREAD

**Issue by ajeetdsouza** [ajeetdsouza/zoxide#45]
I'm planning to introduce some breaking changes to the way zoxide works in the next release. I will put my ideas into the comments below so they can be addressed separately. The idea is that we should do this as little as possible, so we should club the changes to ensure that users are least inconvenienced.

**Comment by ajeetdsouza** [comment]
Instead of using a `String` to represent file paths, we should use the more correct `PathBuf` instead. To do string comparison, we use `to_string_lossy`, with which we can do case insensitive string comparison using [unicase](https://crates.io/crates/unicase), and (hopefully) fuzzy matching too.

**Comment by ajeetdsouza** [comment]
All `zoxide` files should be stored under `"$XDG_CACHE_HOME/zoxide"` using [dirs](https://crates.io/crates/dirs).

**Comment by ajeetdsouza** [comment]
We should introduce a persistent lock file too, which we can call `flock` on to ensure that `zoxide` is thread-safe, using [fs2](https://crates.io/crates/fs2).

**Comment by ajeetdsouza** [comment]
We may want to consider moving away from [bincode](https://crates.io/crates/bincode) for serialization, because although it is the fastest Serde-based serializer/deserializer, it often aborts with a rather unintuitive message (`memory allocation of x bytes failed`) when there is a database corruption.

[This](https://github.com/erickt/rust-serialization-benchmarks) is a useful resource for rust serializers.

**Comment by ajeetdsouza** [comment]
We may want to switch the `Rank` type from `f64` to `i32`. The advantage of using `f64` is that we get more "accurate" ranks, but I do not feel this would impact the algorithm significantly. However, we currently have to convert them to `i64` before sorting by rank due to the fact that floating-point values in Rust do not implement `Ord`.

A nice alternative to this would be to find a nicer way to floating point comparisons.

**Comment by ajeetdsouza** [comment]
Currently, the internal representation of the DB is a `Vec<Dir>`. An alternative to this would be using `HashMap<PathBuf, DirStat>`, which would allow much simpler (and hopefully faster) database additions. Queries would be unaffected.

**Comment by cole-h** [comment]
I can't wait for the switch to `PathBuf`s! I also can't wait for XDG Base Dir spec conformance!

I think fuzzy matching will be a bit of a beast. I have no experience in this area, but I tried the `fst`, `strsim`, `fuzzy-matcher`, `sublime_fuzzy`, and `simsearch` crates, and none were perfect. For example, `strsim` was extremely fast when detecting typos with a Levenshtein distance of 2 or less, while `fuzzy-matcher` and `sublime_fuzzy` didn't really work on typos at all. I didn't put much effort into this experimentation, however, nor did I try to make this work in the case of multiple search strings (e.g. `bz bar` -> `/home/cole/baz/bar`), which will need to be taken into consideration.

Two crates that were on my list to try (but I never got around to) are `rff` and `eddie`. They may or may not be useful.

---

I don't think I agree with switching from `f64` to `i32` "just because" we have to convert it to an `i64` in order to sort. With my currently-meager knowledge, I don't consider this undesirable. I haven't dug into the algorithm we use, but I like how we currently drop entries iff they go below a `Rank` of `1.0`. How would this be achieved if we switched to an integer type? Could you expand on why you're considering this a bit more?

Useful reference: https://floating-point-gui.de/; specifically, https://floating-point-gui.de/errors/comparison/.

---

I'd also like to ask that your open PRs (on your own project, yes) for these changes, so anybody can ask questions about your implementation. You might even get some interested third parties' input on how to improve it in ways you didn't think of.

**Comment by ajeetdsouza** [comment]
Thank you  for the research on fuzzy matching, @cole-h! It is tough to get right, but we will do our best.

Switching `Rank` to `i32` isn't final yet, it was just a thought that occurred to me while making this list. Aging will still work, though - `(1 * 9) / 10` becomes `0`.

And yes, I will definitely open a PR once I start working on this. Also, if you have any further potentially breaking changes in mind, do let me know here.

**Comment by ajeetdsouza** [comment]
Another change that occurred to me - renaming `migrate` to `import`, and creating an `export` subcommand that exports to `z`'s format. This would also be useful to users transitioning from 0.2 to 0.3 (export and then import), and also saves us the trouble of creating a migrate script for every breaking change.
