### ISSUE TITLE
Feature: `zoxide edit` subcommand

### ISSUE THREAD

**Issue by ajeetdsouza** [ajeetdsouza/zoxide#453]
**Functionality**

- Open up `$EDITOR` and display the DB in a human-editable format.
- Wait for the user to make changes.
- Upon exit of $EDITOR, validates the changes and writes them back to the DB.

This approach is inspired by the `visudo` command, which validates your edits upon exit and only then writes to the original file.

**Crates**

- The [edit](https://crates.io/crates/edit) crate simplifies a lot of the work here and seems to have good support for TUI/GUI editors on various operating systems.
- For confirmation prompts, the [dialoguer](https://crates.io/crates/dialoguer) crate is quite popular and seems to support all our use cases.

**Format**

I think a format such as `last_accessed, rank, path` can be aligned well and is quite readable:

```
1662493794,   143.37,/home/foo/bar
1657806644,    64.61,/home/foo/quux
```

The directories would be sorted by path.

**Validation**

- When parsing the file back again, we should call `trim()` on `last_accessed` and `rank` to remove any whitespace.
- We will call `ltrim()` on paths. If they have trailing whitespace, we should print a warning instead.
- We won't bother checking if the directories exist, but we should check that they are absolute paths.

**Errors**

This is how `visudo` handles errors:

```
/etc/sudoers:11:2: syntax error
i
 ^
What now? 
Options are:
  (e)dit sudoers file again
  e(x)it without saving changes to sudoers file
  (Q)uit and save changes to sudoers file (DANGER!)
```

We can do something similar to this:

- When the parsing is successful, print a simple "would you like to save? [y/n]" confirmation.
- When the parsing fails, provide an option to edit again or exit.
- When there are warnings, provide an option to edit again, exit without saving changes, or exit while saving changes.

**Comment by TheRealFalcon** [comment]
@ajeetdsouza , I'd like to work on this if that's ok. A few thoughts/questions:

1. Personally, I prefer no formatting in the editor. I don't think it changes readability, and then there's no spacing to worry about. 
E.g.,
```
1662493794,143.37,/home/foo/bar
1657806644,64.61,/home/foo/quux
```
instead of
```
1662493794,   143.37,/home/foo/bar
1657806644,    64.61,/home/foo/quux
```

2. Once the user has closed the editor (and parsing successful), I'm thinking it'd be easiest to write out a new temporary file, ensure it writes correctly, then overwrite the original. That would be instead of attempting to edit the original file in place.
3. I understand the error/warning prompts, but if the file has been saved, the editor closed, and parsing successful (no errors or warnings), is it necessary to then prompt to save the changes? I would think that saving in the editor would indicate you want to save, and closing without saving would indicate you want to discard changes.
4. Does it make more sense to sort by rank rather than path? There will likely be dozens and dozens (hundreds?) of directories with small (1-4) ranks. If I want to change the rank of a directory, I likely want to change it relative to something that is higher or lower. That's a lot easier to do if you don't have to scroll all around the file to compare ranks.

Thoughts?

**Comment by ajeetdsouza** [comment]
All valid points. I suppose if you sort directories in descending order of rank, they will be mostly aligned anyway.

> Once the user has closed the editor (and parsing successful), I'm thinking it'd be easiest to write out a new temporary file, ensure it writes correctly, then overwrite the original. That would be instead of attempting to edit the original file in place.

The edit crate and zoxide already handle this for you, so you don't need to do anything here.

Other than that, I think your suggestions look great! I'd be happy to review a PR whenever you get time to work on this.
