### ISSUE TITLE
Can't Install On Gentoo

### ISSUE THREAD

**Issue by StathisKap** [ajeetdsouza/zoxide#466]
when I do `sudo emerge --ask app-shells/zoxide`
I get
```
Calculating dependencies... done!

!!! All ebuilds that could satisfy "app-shells/zoxide" have been masked.
!!! One of the following masked packages is required to complete your request:
- app-shells/zoxide-0.8.3-r1::guru (masked by: missing keyword)
- app-shells/zoxide-0.8.2-r2::guru (masked by: missing keyword)
- app-shells/zoxide-0.8.0-r1::guru (masked by: missing keyword)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

Am I doing something wrong?

**Comment by ajeetdsouza** [comment]
I'm not a Gentoo user, so I can't help much here. I did a bit of searching and found this: https://wiki.gentoo.org/wiki/Knowledge_Base:Missing_keywords_and_keyword_requests

The article advises opening a bug if zoxide should work on your system. Since we're using GURU's repository, I'd advise opening a bug here instead: https://bugs.gentoo.org/buglist.cgi?product=GURU

Till then, I'd recommend using the generic installer:

```sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```

Or, install using cargo:

```sh
cargo install zoxide --locked
```
