### ISSUE TITLE
[Feature Support]: use z in pipline

### ISSUE THREAD

**Issue by WingDust** [ajeetdsouza/zoxide#467]
`echo '~/dow/cd' | z`
will no jump to  `'~/dow/cd'`

**Comment by ajeetdsouza** [comment]
Could you explain a bit more about your use case?

**Comment by WingDust** [comment]
looks like `echo '~/dow/cd' | z` 

if `'~/dow/cd'` that never arrived，`z` will not jump

**Comment by ajeetdsouza** [comment]
This seems like a very niche use case so I'd say it's out of scope. However, zoxide is user-extensible by design.

The `z` and `zi` commands are also available as `__zoxide_z` and `__zoxide_zi`. You should be able to initialize zoxide with `zoxide init <shell> --no-cmd` and implement a custom `z` command that reads from stdin and falls back to `__zoxide_z`.

I'm not sure how you'll handle no stdin input without hanging indefinitely, though.
