### ISSUE TITLE
Use nu plugin system

### ISSUE THREAD

**Issue by melMass** [ajeetdsouza/zoxide#480]
Hi,

I wanted to PR it but I'm not fully aware of all the option variations that could affect the template (no-cmd etc...) 
So I'm not sure how to properly tackle it, but here is my version for reference, it's is cleaner than sourcing:

```nu
# =============================================================================
#
# Hook configuration for zoxide.
#

export def-env zoxide_register_hooks [] {
  # Initialize hook to add new entries to the database.
  let-env config = ($env | default {} config).config
  let-env config = ($env.config | default {} hooks)
  let-env config = ($env.config | update hooks ($env.config.hooks | default [] pre_prompt))
  let-env config = ($env.config | update hooks.pre_prompt ($env.config.hooks.pre_prompt | append {
    zoxide add -- $env.PWD
  }))
}


# Jump to a directory using only keywords.
export def-env z [...rest:string] {
  let arg0 = ($rest | append '~').0
  let path = if (($rest | length) <= 1) && ($arg0 == '-' || ($arg0 | path expand | path type) == dir) {
    $arg0
  } else {
    (zoxide query --exclude $env.PWD -- $rest | str trim -r -c "\n")
  }
  cd $path
}

# Jump to a directory using interactive search.
export def-env zi  [...rest:string] {
  cd $'(zoxide query -i -- $rest | str trim -r -c "\n")'
}

```

It changes a bit how the user calls it:

```nu
# config.nu
use plugins/zoxide.nu *
zoxide_register_hooks
```

**Comment by ajeetdsouza** [comment]
Hey @melMass!

> it is cleaner than sourcing

It isn't, because in Nushell the `source` command gets compiled just like you would expect a module to. The primary reason they were looking to deprecate it is that it causes confusion, since it looks similar to the `source` command from other shells.

I do plan to eventually switch over to the `use` syntax, but I'm waiting since the Nushell team isn't fully decided on how they want to handle things like export blocks, and there's no point making users change their configuration twice.

Related: https://github.com/ajeetdsouza/zoxide/issues/456

**Comment by melMass** [comment]
Makes sense! Thanks for the detailed answer!
