### ISSUE TITLE
Ordinary completion with TAB in addition to custom one from SPACE+TAB

### ISSUE THREAD

**Issue by alecandido** [ajeetdsouza/zoxide#484]
I'm already using [fzf-tab](https://github.com/Aloxaf/fzf-tab) for interactive completion, so I appreciate that you do not overwrite with `zoxide` native interactive completion, keeping it on `<SPACE><TAB>`.

Still, I would like the same completion list that is available to `<SPACE><TAB>` to be provided to ordinary ZSH completion if I press just `<TAB>`.
In this way, I'd be able to use just `<TAB>` to get interactive completion, in a consistent way with all the other commands (as it was working for `fasd`, that I was using before).

**Comment by y1rn** [comment]
I prefer use `<TAB>` to open query and  press `<ENTER>` cd to dir directly. Is there any setup guide?

**Comment by y1rn** [comment]
I'm using [fzf-tab](https://github.com/Aloxaf/fzf-tab) with follow configuration, looks good:
```
eval "$(zoxide init zsh --cmd cd)"

__zoxide_z_complete () {
  args=$(zoxide query -l)
  _arguments "1:profiles:($args)"
}
#fzf-tab config
zstyle ':completion:*:__zoxide_z:*' sort false

```

**Comment by ajeetdsouza** [comment]
@alecandido the good thing about Space+Tab (on the latest zoxide) is that it performs the `cd` directly instead of simply completing the command.

The way `z` is designed to be used is:

- Within a directory, it is a drop-in replacement for the `cd` command. Early on in this project, I programmed `z` just to jump, and used `cd` otherwise - but I found that it was hard to build muscle memory for this. Every time I changed directories, I would have to remind myself to "jump" there. The benefit of a single command to do both is that you quickly learn to always use `z`.
- Mostly, when jumping, just a couple of characters tend to be good enough. However, by nature of the tool, queries are ambiguous - so I added a Space+Tab feature so that people could review the list of options before jumping. On the latest version of zoxide, this is a faster workflow than fzf-tab - because fzf doesn't "complete" the command - it directly jumps to the selected directory.

I'd strongly encourage you to try this out on the latest version of zoxide. If you'd still like to program your own completions, you can get them using `zoxide query --list <keywords>`.

**Comment by alecandido** [comment]
In the meanwhile, I started using [`carapace`](https://carapace.sh/) for the completion, it gave exactly what I wanted (tab completion, and no direct `cd` on completion selection).

I acknowledge it doesn't have to be necessarily this way, it is highly personal. Thank you very much for your kind reply :)
