### ISSUE TITLE
More recent version in Ubuntu 22.04

### ISSUE THREAD

**Issue by timkgh** [ajeetdsouza/zoxide#509]
Ubuntu 22.04 has `zoxide v0.4.3-unknown` which is old and has some issues with `zsh`.

Not sure whether it depends on you to make the latest zoxide available to `apt` in Ubuntu, or someone else.

**Comment by ajeetdsouza** [comment]
This is unfortunately a very common problem with Debian / Ubuntu based systems and there isn't much I can do about it. You could _probably_ try [reporting a bug](https://www.debian.org/Bugs/Reporting) to Debian and inform them that since this is a shell plugin it needs to be updated more frequently.

For now, I'd recommend simply using the shell installer:

```sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```
