### ISSUE TITLE
zoxide v0.9.0 breaks TAB completion for fasd

### ISSUE THREAD

**Issue by timkgh** [ajeetdsouza/zoxide#524]
I have zoxide configured to take over `cd` in zsh. Until 0.9.0, I was able to still use fasd to do things such as `cd d,tmp<TAB>` but now it does not seem to work anymore. If I don't let zoxide take over `cd`, it works.

**Comment by ajeetdsouza** [comment]
That's because zoxide has its own implementation for tab completions. Have you tried the `<space>+<tab>` completions mentioned in the README?

**Comment by timkgh** [comment]
Yes, I'm aware of `<Space><TAB>`. But `<TAB>` didn't use to break `fasd` before 0.9.0, *I think*.

**Comment by ajeetdsouza** [comment]
I checked, there doesn't seem to be any major change to how we're doing completions since they were first introduced. My guess is you were using a version of zoxide that didn't have space-tab completions.

Since zoxide isn't really doing anything special with completions (it's just adding them using compdef), I suggest reporting this issue on fasd's tracker.
