### ISSUE TITLE
Better matching, fuzzy matching, ignore non-alpha chars

### ISSUE THREAD

**Issue by timkgh** [ajeetdsouza/zoxide#525]
I'm surprised to see that if I have directories such as `a-b`, `a_b` in zoxide, `cd ab` doesn't work.

Any plans for better matching, fuzzy matching, ignoring special/non-alpha chars, etc?

**Comment by ajeetdsouza** [comment]
- What do you mean by "better completions"?
- IMHO, since our queries typically have very few characters, fuzzy matching doesn't make sense to do. For example, changing one character in a 4-character query is a 25% change to the input! In my experiments, this just ends up producing bad results.
- Since `-` and `_` are typically used to separate words, ignoring them would worsen the algorithm for most users. In your example query, you would typically use `cd a b`. There's a space separator because there are two different words in the input.

Regarding improving queries, I do plan to add smartcase and diacritic normalization, which should improve things for some users.

**Comment by timkgh** [comment]
Sorry, I meant to say better matching. 
I was not aware I could use spaces instead of `-` and `_`.

**Comment by ajeetdsouza** [comment]
No problem, I'll close this issue since none of these features are planned.
