### ISSUE TITLE
Proposal: new subcommand to delete zoxide data

### ISSUE THREAD

**Issue by ajeetdsouza** [ajeetdsouza/zoxide#58]
Use cases:

- Users who want a fresh start
- Resolving database corruptions

**Comment by cole-h** [comment]
I think I'm -1 on this. If a user wants a fresh start or wants to resolve database corruptions, they should just delete the database by hand with `rm ~/.local/share/zoxide/db.zo` (or wherever they put it). This way it's unambiguously being removed, permanently and with no chance of recovery.

A subcommand that prints the in-use DB's path might be useful to assist in that, but I don't think something this destructive should be possible -- at least not without a LOT of warnings, confirmations, and trapdoors to escape through.

**Comment by ajeetdsouza** [comment]
Deleting the database by hand is rather painful for Windows/macOS users, since the DB path is not as memorable.

**Comment by cole-h** [comment]
That's a fair point. I'd still prefer if it wasn't baked in and instead something that would have to be done manually. Something like:

```shell
$ zoxide db-path # or some other subcommand name
"/Users/Alice/Library/Application Support/zoxide/db.zo" # quoted because of the space, just to be safe

$ rm "$(zoxide db-path)"
```

This way, the user expresses their intent to delete the database and all responsibility falls on them, rather than going up through their shell history, seeing `zoxide` and pressing enter, not noticing the fact that it actually said `zoxide remove-db` (a contrived example, but hopefully you see my point)

**Comment by ajeetdsouza** [comment]
That does make sense, although that risk would be removed if we added a confirmation prompt. 

I understand why you're against this, but I think something like `zoxide clear` would be a lot more intuitive - the user shouldn't have to deal with zoxide data manually.

**Comment by cole-h** [comment]
I suppose as long as there are safeguards in place, I'm neutral on this (still leaning negative, though).
