### ISSUE TITLE
directories aren't saved at all

### ISSUE THREAD

**Issue by iam-angel-val** [ajeetdsouza/zoxide#607]
I'm using nushell. Whether I use `z` or `cd` to change directories, running `z` or `zi` always returns an error and there's nothing new in the db file. What's weird is that it worked for the first few directories right after I installed, but after then it just stopped working. Unfortunately this was a couple of days ago so I can't remember if i did anything to make it happen.

**Comment by Ghoughpteighbteau** [comment]
seeing this as well, Just playing with it though, it seems the hook to add directories isn't working as expected. if you manually call `zoxide add ` then you can jump to them as expected.

A hack to work around this issue is to edit the `~/.zoxide.nu` file and comment out the code that inserts the hook

```nushell
## Initialize hook to add new entries to the database.
#if (not ($env | default false __zoxide_hooked | get __zoxide_hooked)) {
#  $env.__zoxide_hooked = true
#  $env.config = ($env | default {} config).config
#  $env.config = ($env.config | default {} hooks)
#  $env.config = ($env.config | update hooks ($env.config.hooks | default {} env_change))
#  $env.config = ($env.config | update hooks.env_change ($env.config.hooks.env_change | default [] PWD))
#  $env.config = ($env.config | update hooks.env_change.PWD ($env.config.hooks.env_change.PWD | append {|_, dir|
#    zoxide add -- $dir
#  }))
#}
```
then in your nushell config `~/.config/nushell/config.nu`, modify the hooks section to include adding a directory to zoxide

```nushell
    hooks: {
        pre_prompt: [{ null }] # run before the prompt is shown
        pre_execution: [{ null }] # run before the repl input is run
        env_change: {
            PWD: [{|before, after| zoxide add -- $after }] # run if the PWD environment is different since the last repl input
        }
        display_output: "if (term size).columns >= 100 { table -e } else { table }" # run to display the output of a pipeline
        command_not_found: { null } # return an error message when a command is not found
    }
```
seems to work after that.

**Comment by iam-angel-val** [comment]
thanks, that works.
