### ISSUE TITLE
Proposal: switch to TOML config files instead of using environment variables

### ISSUE THREAD

**Issue by ajeetdsouza** [ajeetdsouza/zoxide#61]
**Advantages:**

- Richer data structures allow us to represent things like lists (eg. #48, #60) in a more user-friendly manner. Being a specialized format, it also reduces the change of parsing errors (see #48 - what if a directory had a `:` in the name?).
- It is less prone to human error, since an misspelled/deprecated variable in the config file will throw an error/warning immediately.
- Config files, IMHO, tend to be a lot more manageable than environment variables, and can be backed up along with the rest of one's dotfiles. An additional advantage here is that one can use the same config file across shells.

@cole-h presented some [interesting insight into the issue](https://github.com/ajeetdsouza/zoxide/pull/60#issuecomment-611055973), and I'll add my comments here:

> Want to test something? _ZO_DATA_DIR=/tmp/zo zoxide add /tmp. Want to change the max age for a single shell session? export _ZO_MAXAGE=9999 (or however you achieve that in any arbitrary shell).

I think this is a fairly limited use case, and isn't likely to affect most people. For the people that need it, they can keep an editor open with a temporary config file and change it as desired.

> If we ship a default configuration file, we then have to make sure users know when new options are added, or options are deleted/deprecated. If we don't ship a default configuration, we have to make sure users know how to create their own.

We will ensure that `zoxide` works out of the box with zero configuration. The only use of the config file is for those users that would like to change the default behaviour.

> It also becomes another folder related to zoxide on users' filesystems: their local data dir for the database itself, and now the config dir for the configuration file.

This is true, but since the user never has to deal with the data directory, it mostly just becomes an issue of managing the one config file (versus managing environment variables in one's shell rc file).

> The file format itself also brings with it a whole host of issues, see: the many different "bugs" filed on Alacritty's issue tracker about configuration -- improper indentation, duplicate keys, unused keys, etc., in their case of YAML.

Looks like they're seriously considering shifting to TOML too, since YAML is too error-prone as a file format. They do mention that [TOML would solve most issues](https://github.com/alacritty/alacritty/issues/3467#issuecomment-603818600), though.

Another disadvantage I can think of is that this will likely result in a slight slowdown, since we have to read another file, and, unlike environment variables, we can't selectively parse only the values that we need. That said, this shouldn't be a very significant slowdown, and I think we should favour usability over speed.

**Comment by cole-h** [comment]
This might be a little less coherent than usual, because as I was about to
submit my original rebuttal, the power went out (and I was drafting in GitHub's
textbox... lesson learned).

---

I strongly recommend against dropping environment variables altogether. Despite
it being a "fairly limited use case," it is one I rely on when testing. It would
extremely inconvenient to "keep an editor open with a temporary config file and
change it as desired."

Take, for example, if we were to move to TOML-only right this moment: once the
`_ZO_FZF_ARGS` PR is merged (assuming it changes from an env var to the expected
configuration file), I would want to decrease the height of `fzf` with its
`--height` flag. If we drop environment variables altogether, this would look
like the following:

1. `nvim ~/.config/zoxide/config`
2. edit value
3. save file
4. `zoxide query -i`
5. decide if I'm satisfied; else, go back to 2

With the environment variable, I would only need to 1) `_ZO_FZF_ARGS="--height 20%"
zoxide query -i`, and 2) decide if I'm satisfied; if not, press the up arrow and
change `20%` to something else.

I think we should be careful with adding features that will "result in a slight
slowdown," no matter how "slight" that turns out to be. As the README stands
today, it claims that `zoxide` is a "blazing fast alternative to `cd`," which
implies (to me) that we value speed above all else. If we start adding features
under the guise of a "slight" performance impact, they will add up to the point
where they are no longer just "slight" differences.

We could compromise with feature flags: `toml` for a configuration file and
`env` for environment variables. Ideally, both would be allowed at the same
time, with environment variables taking precedence over the config file (in
order to support my usecase of testing and overriding on a per-shell basis).

Overall, I'm not opposed to adding a configuration file because you propose
valid points, such as being cross-shell compatible and having richer data
structures, as long as we **do not drop environment variables**.

(As an aside, to rebuke your "colon in ignored path" example: it's on the user
to escape the colon, just like in the system-wide PATH. If, due to not escaping
the colon, it results in unexpected ignores, it is most definitely not our
fault.)

**Comment by ajeetdsouza** [comment]
Those are fair arguments. I don't think the development cost of supporting TOML and environment variables is justifiable at the moment, so I'm going to put this one on the backburner for now.
