### ISSUE TITLE
Tab key conflict between Zoxide and Warp terminal

### ISSUE THREAD

**Issue by danulqua** [ajeetdsouza/zoxide#614]
I use [Warp terminal](https://www.warp.dev/) and I've just installed Zoxide, it seemed like a very useful CLI tool, but there is an issue. Tab key triggers Zoxide's fuzzy search to choose the correct directory for navigation, but in Warp it triggers autosuggestions and it has higher priority so the Zoxide's fuzzy search doesn't work.

What can you suggest to benefit from both tools?

**Comment by Treborium** [comment]
Same here. I installed zoxide via home brew. Tab completion works on the built in macos terminal but not with warp

- zoxide version `0.9.4`
- warp version `v0.2024.07.23.08.02.stable_01`

**Comment by Morette** [comment]
still facing this issue
warp v0.2024.07.30.08.02.stable_01
zoxide 0.9.4

**Comment by ajeetdsouza** [comment]
Warp does things a little differently from other terminals.

To the best of my knowledge (I don't work at Warp), the way they're able to create an IDE-like typing experience is because you're essentially typing in a text box that has nothing to do with the shell. Warp does not send anything to the shell till you press Return. The downside is that some shell features like completions no longer work with Warp. They work around the problem by using [Fig](https://github.com/withfig/autocomplete) completions for popular commands, but it's not likely we'll see custom completions like Space+Tab anytime soon.

> I had wondered about this, its peculiar since its sponsored by warp too...

I had been using Warp for around a year before they approached me for a sponsorship, and I still do. While I miss Space+Tab, the benefits for me far outweigh the downsides.

---

I'm closing this issue since nothing can be done about it, but if Warp ever creates a way to plug into the completions system, I'd be more than happy to fix Space+Tab.

**Comment by ElijahLynn** [comment]
I updated the README to clarify that TAB doesn't work with Warp and linked to your comment above. 

* https://github.com/ajeetdsouza/zoxide/pull/989

**Comment by smeeklai** [comment]
I was figuring out and found this. Thanks for the info. Would be great to have the PR merged.
