### ISSUE TITLE
zoxide init ion

### ISSUE THREAD

**Issue by shouze** [ajeetdsouza/zoxide#66]
Would be nice to support [ion shell](https://github.com/redox-os/ion) too :angel:.

**Comment by ajeetdsouza** [comment]
Ion definitely does look interesting, but I'm not familiar with the syntax. Is there a mechanism for prompt/pwd hooks?

If you can make a PR adding Ion support, I would be happy to merge it!

**Comment by kolia** [comment]
ion currently [does not allow functions to be called with different numbers of args](https://gitlab.redox-os.org/redox-os/ion/issues/834), unless the args are passed in as an array. So in practice, you'd need to write `z [ query ]` instead of `z query`.

With that caveat, here is an `ion` script that would be equivalent to the output of `zoxide init` for other shells:

```
fn _z_cd argv[]
    cd @argv || exit
    exists -s _ZO_ECHO && echo $PWD
end

fn _z_fn argv[]
    match @argv
        case [-]
            _z_cd @argv || exit
        case _
            let result = $(zoxide query @argv)
            if test -d $result
                _z_cd [ $result ] || exit
            else if test -n $result
                echo $result
            end
    end
end

alias zi='z -i'
alias za='zoxide add'
alias zq='zoxide query'
alias zr='zoxide remove'
```

Adding a hook that calls `zoxide add` would require adding `zoxide add` to the `fn PROMPT` function definition, which is how ions let users customize their prompt. Not sure how one would set that hook up by running `eval $(zoxide init ion)`, best is probably to ask users to add `zoxide add` to their PROMPT by hand. There is also no way to call `zoxide add` when `PWD` gets modified, as far as I can tell.

**Comment by ajeetdsouza** [comment]
@kolia I had a look at `ion` today. I'm not a fan of changing the `z` syntax specially for `ion`, and having the user specifically add `zoxide add` to their shell also seems less-than-ideal.

However, there doesn't appear to be a better way to do this at the moment, and your implementation does work well. Feel free to create a PR with these changes!

**Comment by kolia** [comment]
Sure I could make a PR.

I’ve also opened an issue about for ion https://gitlab.redox-os.org/redox-os/ion/issues/962, alternatively we could wait and see.

**Comment by ajeetdsouza** [comment]
Yes, I too think waiting is a good idea for now. We can pick this up later if they decide against implementing variadic functions.

Thank you for your work on this!

**Comment by ahkrr** [comment]
@kolia @ajeetdsouza  regarding the issue of adding the `_zoxide_hook` to the `HOOK_PROMPT` 
one solution that currently works for me is 
```
fn _zoxide_hook
    zoxide add
end

if not matches $PROMPT '.*?_zoxide_hook.*?'
	let PROMPT ::= "\$(_zoxide_hook)"
end
```

**Comment by ajeetdsouza** [comment]
@ahkrr, from what I've read, `PROMPT` could either be a variable or a [function](https://doc.redox-os.org/ion-manual/html/misc/06-prompt_fn.html), so both cases need to be handled.

**Comment by ahkrr** [comment]
@ajeetdsouza I have no idea what to do if a user supplied a `fn PROMPT` [function](https://doc.redox-os.org/ion-manual/html/misc/06-prompt_fn.html), maybe encourage the user to work with the variable instead. 
Another problem aside from the variadic functions is this:

For me in ion `echo $(zoxide query -i)` and `echo $(fzf)`
don't interactively print to the terminal. It is executing in the background and after entering a string and pressing enter you get the result but I wouldn't call that _interactive_.
`echo $(sk)` this works interactively. [sk](https://github.com/lotabout/skim) is basically a rust version of [fzf](https://github.com/junegunn/fzf)

A this point I also think that it is problematic to implement ion support. For the ones that are interested in ion, at this point in time they should probaly put this manually into their shell.

**Comment by matu3ba** [comment]
Let me summarize what to implement in the ion REPL as a [sort of plan](https://gitlab.redox-os.org/redox-os/ion/-/milestones/3), once we get the grammar formally defined and the parser rewritten in a more robust way:
Side-note: Scripts must be in a "safe mode", so one needs to write ${variable}[range] or @{variable}[range] (this is also (posix) shell best practice). I do intend shortcuts for adding and removing different types of braces, but especially ranges with arbitrary stepping should become extremely tricky.

1. REPL must differentiate between status line, cursor symbol and cursor field.
2. Ideally REPL can properly handle background processes with counters, so one does not need [ugly hacks](https://github.com/starship/starship/blob/8ad0e9e00c850399449fefa6fede742295927c46/src/init/starship.ion#L12-L13). (Background processes are currently broken, so they hack around.)
3. I think hooks are a poor abstraction, when you know when things will happen. When we get working function returns, pwd can be used with the path before and after changing directories.
4. Alias functions will start with capital letters, if they are needed (I am not convinced yet).

**Comment by ajeetdsouza** [comment]
Hey @matu3ba, thanks for the update!

> I think hooks are a poor abstraction

How so? I didn't exactly understand the alternative you proposed, could you elaborate?

> I am not sure how to achieve this at best without exploding complexity

Admittedly, designing a shell is much harder than designing a programming language, because you have to ensure that it's easy enough for anyone to read/write, concise enough to be able to do a lot of work in a single line of code, and yet powerful enough to write scripts with. 

I have no experience with programming language design, but I'm interested - could you explain why the `mut` keyword was introduced, and why references are necessary?

**Comment by matu3ba** [comment]
> Hey @matu3ba, thanks for the update!
> 
> > I think hooks are a poor abstraction
> 
> How so? I didn't exactly understand the alternative you proposed, could you elaborate?

You want to (over)write the shell configuration to have defined entry- and exit-points from what the shell is doing (on user keypress), since that is way simpler, has less delay etc.

> 
> > I am not sure how to achieve this at best without exploding complexity
> 
> Admittedly, designing a shell is much harder than designing a programming language, because you have to ensure that it's easy enough for anyone to read/write, concise enough to be able to do a lot of work in a single line of code, and yet powerful enough to write scripts with.

And fast for the use case (batch processing = nu or individual processing = ion). Other shells use more tradeoffs (zsh, bash etc), but are still complex beasts. Or they are okay with being slower (fish). Dash is comparable (with less functionality), but it is very difficult to safely optimise C code (and you get some parsing+evaluation overhead of POSIX shell requirements).

> 
> I have no experience with programming language design, but I'm interested - could you explain why the `mut` keyword was introduced, and why references are necessary?

Copy-assign is always slower, since you need to allocate a not efficiently precomputable space (depends on context of execution). Hence you want `mut` and for safe usage of other accessible scopes references for functions.

Personally, I would also like to restrict the access to other scopes, but that are some rules for the future to do.

**Comment by ajeetdsouza** [comment]
Hm, doesn't the absence of `let` imply `mut`? Or has it been added to make mutations more explicit?

**Comment by matu3ba** [comment]
> Hm, doesn't the absence of `let` imply `mut`? Or has it been added to make mutations more explicit?

`let` can shadow variables in functions, like in the following:

```sh
let var:int = 1;
let stuff:int = 2;
  fn testme
    let var:int = 3;
    mut stuff = 42;
    echo $var
  end
testme
echo $var
echo $stuff
```
```txt
3
1
42
```

We could also use `local` etc, but thats too long and variables should be ALWAYS local (or explicitly written global environment variables).

**Comment by ajeetdsouza** [comment]
I'm closing this issue for now. The related Ion issue (https://gitlab.redox-os.org/redox-os/ion/-/issues/834) has been open 4 years without a conclusion, so it's unlikely we'll be able to support it in the near future.

Feel free to reopen / create a new issue once Ion adds enough functionality / stability to support something like this.
