### ISSUE TITLE
zoxide cannot find the `cd` command

### ISSUE THREAD

**Issue by UtkarshVerma** [ajeetdsouza/zoxide#686]
I have a common shell configuration file named `shellrc` where I initialise `zoxide` as follows:

```sh
if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init posix --hook prompt)"
fi
```

This works and in my `zsh` shell, I can see the `z` command. However, when I try to open a directory, I get the following:

```console
$ z downloads
__zoxide_cd:2: command not found: cd
```

I have investigated this to be caused by the following implementation.

```sh
__zoxide_cd () {
    \command cd "$@"
}
```

Here is what fails on `zsh`:

```console
$ command cd
zsh: command not found: cd
```

This works on other shells like `dash` and `bash`.

**Comment by UtkarshVerma** [comment]
I am using v5.9.

```console
$ zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
```

**Comment by ajeetdsouza** [comment]
zsh appears to differ from POSIX shells here. Whereas in other shells you would use `command cd`, on zsh you need to use `builtin cd` unless the `POSIX_BUILTINS` option is set.

Possible solutions:

- We could add custom logic to the POSIX script to handle zsh. However, given that there is a dedicated initialization script for zsh, I don't think it makes much sense to do that.
- You could initialize zoxide in the RC file of each shell, rather than have a common one for all shells. This way, you will also get access to shell completions.
- Enable `POSIX_BUILTINS` in zsh. This will make zsh POSIX-compliant, and zoxide will start working again.

**Comment by UtkarshVerma** [comment]
Thanks, using `setopt posixbuiltins` did the job for me.
