### ISSUE TITLE
Update the `zoxide init nushell` script.

### ISSUE THREAD

**Issue by Oglo12** [ajeetdsouza/zoxide#699]
Nushell has changed some things, so this command doesn't work. It is outdated.

**Comment by ajeetdsouza** [comment]
Have you tried installing the latest version of zoxide?

```
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```

**Comment by disconsis** [comment]
I had a similar issue - nushell complains about `def --env` not being valid in the init script. However it turns out I just have an older version of nushell (0.84) and just saw that only 0.89+ is supported.
Might be a good idea to check the version on startup?

There's problems with that though. Since nushell will parse the script _before_ running it, if running the script with an older nushell version it won't be able to even run it.

**Comment by disconsis** [comment]
There's hacks around that, but it might (probably?) not be worth it.

**Comment by ajeetdsouza** [comment]
Your version of zoxide is out of date. This is fixed on v0.9.3.

**Comment by disconsis** [comment]
I am on 0.9.3

```
ketan@wsl:/tmp/foo$ zoxide --version
zoxide 0.9.3
```

**Comment by ajeetdsouza** [comment]
@disconsis have you updated to the latest version of Nushell as well? Nushell is pre-1.0, every few versions there are breaking changes, so you need to be on the latest versions of both.
