### ISSUE TITLE
Substitute and not go to the directory when  _ZO_ECHO='1'

### ISSUE THREAD

**Issue by ashiquelal** [ajeetdsouza/zoxide#739]
I have set _ZO_ECHO='1'. Is it possible to make zoxide work such that when I type z <directory>, it autocompletes but doesn't go to the directory?

I am using ZSH with Oh-my-zsh.

**Comment by ajeetdsouza** [comment]
Could you describe your use case?

**Comment by ashiquelal** [comment]
Right now, if I type "z dir_name" and press tab. I directly goes into that folder. I want it to just turn it into "z absolute_path_to_dir". Similar to how zsh_z works. This is so that I can edit the path.

**Comment by ajeetdsouza** [comment]
I'm assuming you're referring to the new space-tab feature where you can select a directory from the interactive picker and zoxide immediately cd's to it.

This is intentional, zoxide is designed to make your workflow as fast as possible. There will of course be specific instances where it doesn't work - the only thing that will work consistently every time is the original `cd` command. The idea of zoxide is to take shortcuts to save you time on 90% on your `cd` invocations.

Unless there is more demand for a feature like this, it's hard to justify slowing down most space-tab invocations to speed up this particular workflow.
