### ISSUE TITLE
unknown option: --keep-right zoxide: fzf returned an error

### ISSUE THREAD

**Issue by igormcsouza** [ajeetdsouza/zoxide#790]
It looks like this error is related to zoxide using newer features but my OS has an older version for fzf..

On the official documentation for fzf it asks to use 0.20.0 on ubuntu 20.04, so that's what apt installs on my machine! Not sure if I should force a newer version that.. since fzf can break and causes issues! Maybe zoxide can checkout what version of fzf to use or default to 0.20.0 which works on major distributions!

See #405

**Comment by ajeetdsouza** [comment]
Unfortunately, it is hard to justify supporting something like this:

- Ubuntu 20.04 is 4 years old now.
- Ubuntu and derivatives are generally notorious for not updating any of their dependencies, even on the latest version. In our own issue tracker, we see a lot of users who ran `sudo apt install zoxide`, ended up with an old version, and encountered bugs that have been fixed since years.
- fzf itself is not a system dependency - it can easily be upgraded without breaking anything.
- Almost every other distro has upgraded to a later version of fzf. The minimum fzf version we rely on is 2 years old.

**Comment by dangarciahe** [comment]
The reasons given by ajeetdouza are very reasonable. In ase anyone encounters the same issue, I installed fzf on Ubuntu 20.04 using Git, following their instructions: https://github.com/fuzzy-finder/fzf?tab=readme-ov-file#using-git.

That solved the compatibility issue.
