### ISSUE TITLE
Strange score mechanism

### ISSUE THREAD

**Issue by RichyMong** [ajeetdsouza/zoxide#874]
Hello, thanks for the great tool. However, I do have some problems to make it work correctly. 
For the following query, I expected the second entry had a higher score but it didn't although its name matched the query string exactly. I also tried to add '$' to the pattern but it seems that zoxide doesn't handle it at present.
![image](https://github.com/user-attachments/assets/ad9a87b8-01a4-4331-b936-8fc4731d321e)

**Comment by ajeetdsouza** [comment]
The score is based on recency and frequency of use, not the search keywords.

The search is intentionally kept simple in order to be predictable - the idea is that you should already know where `z` is going to take you, even if that means the algorithm is not as powerful.

https://github.com/ajeetdsouza/zoxide/wiki/Algorithm
