### ISSUE TITLE
Publish last tag on chocolatey

### ISSUE THREAD

**Issue by LoicRiegel** [ajeetdsouza/zoxide#880]
and possibly other package managers, I haven't checked.

### Problem:
Current version of zoxide in chocolatey is 0.9.2 (see [versions](https://community.chocolatey.org/packages/zoxide#versionhistory)), which has bug which makes zoxide impossible to use: sourcing the generated `.zoxide.nu` does not work

![2024-09-04_11h18_11](https://github.com/user-attachments/assets/e32c934a-dfd9-4062-9808-2b20211c8a06)

I'm using the latest version of nushell, `0.97.1`.

Note that the problem also appears when installing zoxide 0.9.2 with cargo

### Workaround
Install zoxide 0.9.4 with cargo -> everything works fine

### Suggestions for how to fix:
- Publish zoxide 0.9.4 on chocolatey
- Optional: same for other package managers if they also don't have the latest version
- Optional: add/update GitHub workflows to automatically publish to all package managers every time a new git tag is created?

**Comment by ajeetdsouza** [comment]
I don't maintain the Chocolatey package, you may have to report it to the maintainer of zoxide's Chocolatey package. In the meantime, you can use `winget` - it's builtin on Windows and always points to the latest version.

**Comment by stonkie** [comment]
@ajeetdsouza It may be worth removing the choco package from the Windows installation instructions as it's getting pretty old. The published version doesn't work with the latest nushell for example and I'm sure it's confusing a lot of people needlessly...

**Comment by LoicRiegel** [comment]
Would it be possible for your team to take ownership of the choco package? Cause choco is nice to use, and I think a lot of people would be grateful to have zioxide released there as well. Or do you prefer not to add this to your workload?

**Comment by ajeetdsouza** [comment]
@LoicRiegel unfortunately, there's no team - I'm the sole maintainer of zoxide. Packaging of zoxide for various package managers is currently taken up by maintainers from the community that I'm truly grateful for. I don't think it would be possible for me to take up maintenance of the Chocolatey package right now, especially since I don't use Windows / Chocolatey myself.

If you're on Windows, the recommended way to install zoxide is via `winget`, which is built into Windows. There's a GitHub Action [here](https://github.com/ajeetdsouza/zoxide/blob/main/.github/workflows/winget.yml) that publishes to Winget every time there's a new release, so it's always up-to-date. I'd be happy to accept any PRs that do the same for Chocolatey!

**Comment by LoicRiegel** [comment]
@ajeetdsouza my bad, I didn't know it was only you! Thanks a lot for your response.
I also think having an automated process like winget would be super nice, I would love to help here but I would need access to the zioxide choco package to be able to publish. I have contacted the maintainer by email, I will wait for his answer and I'll keep you updated here

**Comment by sitiom** [comment]
@LoicRiegel Hi, apologies for the late response. If you have the automation and repo set up, I can transfer the ownership to you.

As you can see, I have already switched to Winget a long time ago (and contributed to the Winget Releaser action mentioned above). I suggest you give Winget a try 🙂.

**Comment by LoicRiegel** [comment]
@sitiom thx for your response! I don't the automation right now, but I can work on it. I'll get back here when I do.

**Comment by LoicRiegel** [comment]
Actually @sitiom , I took a closer look at [your repo](https://github.com/sitiom/chocolatey-packages/tree/main) and everything looks good, and I see a GH action workflow supposed to run periodically (I don't see the actual workflow runs, though).
I mean, looking at this, I think it would be easier and faster to keep your repo, and just make the automatic update work again. Do you agree?

Do you see the [ci](https://github.com/sitiom/chocolatey-packages/blob/main/.github/workflows/ci.yml) workflow runs on your side?

**Comment by sitiom** [comment]
Apologies for the late reply. I had encountered some issues with my other packages, and since I'm no longer using Chocolatey myself, I decided to disable the actions on my repository.

However, I'd be happy to transfer ownership if someone is willing to set it up and maintain it independently. Feel free to copy from my repo if you'd like 🙂
