### ISSUE TITLE
`z rustfmt` navigates to an incorrect `rustfmt` directory

### ISSUE THREAD

**Issue by rufevean** [ajeetdsouza/zoxide#892]
## Description
I encountered an issue when trying to navigate to a directory containing `rustfmt` using zoxide. I expected `z rustfmt` to take me to the directory I was currently in, where `rustfmt` is present. Instead, it forwarded me to a different directory that also contains `rustfmt`.

## Steps to Reproduce
1. Be in a directory that contains a `rustfmt` binary or folder (e.g., `/path/to/my-project/rustfmt`).
2. Run `z rustfmt` from the terminal.
3. Observe that zoxide forwards you to another directory (e.g., `/other/path/to/rustfmt`).

## Expected Behavior
I expected `z rustfmt` to prioritize the `rustfmt` directory in the current context .

## Actual Behavior
`z rustfmt` navigates to a different `rustfmt` directory, ignoring the current context.

**Comment by ajeetdsouza** [comment]
That's the expected behaviour - the directory you're currently in is excluded from the `z` results. So if you're in the best match, you will end up jumping to the second best match.

This is especially useful in cases where zoxide jumps to the wrong directory - you can just re-run your previous command and it will jump to another match.
