### ISSUE TITLE
zoxide prefers more popular over exact

### ISSUE THREAD

**Issue by tekumara** [ajeetdsouza/zoxide#91]
```
$ zq -i setup
162       /Users/tekumara/code/setup
189       /Users/tekumara/code/dt-setup
```
zoxide will prefer `dt-setup` when I was expecting the more exact `setup`

**Comment by ajeetdsouza** [comment]
I think the strength of zoxide's matching algorithm lies in its predictability - it simply matches every keyword along the path and ensures that the last keyword matches the directory name. This means the following would match:

- `z /setup`
- `z /set`

it would match the first result, but not the second, since the latter does not have a `/` immediately before `setup` in its path.

This can sometimes be a problem - for example, `/code/setup` cannot be distinguished from `/code/setup-dh` in this manner. In cases like these, I would use `zi set`and select the correct option. I admit that this is not the most ideal solution, but I'm not convinced that prioritizing exact matches would improve results.

If we changed the algorithm to treat `z setup/` as a path ending in `setup`, would that benefit you?

**Comment by tekumara** [comment]
I would probably use `z setup/` if it were available. 

BTW is there any doco that explains the matching logic?

**Comment by ajeetdsouza** [comment]
Not at the moment, no. I'll put in a section into the README once I'm free.

**Comment by tekumara** [comment]
That would be awesome thank you @ajeetdsouza 🙏 I've found your explanations in issues really helpful.

**Comment by ajeetdsouza** [comment]
Added an explanation to the [Wiki](https://github.com/ajeetdsouza/zoxide/wiki/Algorithm#matching).
