### ISSUE TITLE
Idea: merge `z` and `zi` - enter interactive mode by using `z` without argument

### ISSUE THREAD

**Issue by WieeRd** [ajeetdsouza/zoxide#932]
Currently, `z` without any argument changes cwd to the home directory.
I assume this is meant to replicate the behavior of `cd`, but I don't find this particularly useful.
Wouldn't it be much more useful and ergonomic if `z` without any argument enters the interactive mode of `zi`?

**Comment by ajeetdsouza** [comment]
This is certainly a nice idea. The problem is that opening up `zi` with no arguments typically produces too many results and is not very helpful. I personally tend to prefer Space+Tab completions where I can type out some part of the query before opening up the fuzzy finder.

However, if you'd like to set it up on your own shell, you can just create a function that wraps `__zoxide_z` (the equivalent of "z") and calls `__zoxide_zi` (equivalent of "zi") when there are no arguments.
