### ISSUE TITLE
fish doesn't cd into the directory

### ISSUE THREAD

**Issue by fi0** [ajeetdsouza/zoxide#97]
fish, version 3.1.2
zoxide version 0.4.3
After `zoxide query keyword`, or `zoxide query -i`, the path is printed. But it doesnt cd into the dir.

**Comment by ajeetdsouza** [comment]
Hey @fi0,

`zoxide query` is only supposed to print out matches, not cd into them. Once you've [initialized zoxide](https://github.com/ajeetdsouza/zoxide#step-3-adding-zoxide-to-your-shell), the `z` and `zi` functions will be defined in your shell. You can use `z foo` to cd into a directory matching `foo`, or use `zi foo` for interactive selection.

Do let me know if you have further questions!

**Comment by fi0** [comment]
thank you! 
I think there was an alias zi that maps to z -i. So it didnt work.
I've fixed it now.

**Comment by cole-h** [comment]
Just to provide some context: I just realized I had the same problem with `zi` not working. This is because, in the past, we had a `zi` abbr: 

https://github.com/ajeetdsouza/zoxide/blob/4731533352ad3d900316cf38d9fab6c6d7c48a2a/src/subcommand/init/shell/fish.rs#L62

, but abbrs are universal by default (e.g. they persist after being set). After we changed `zi` to be a function rather than an abbr, the abbr stayed around, causing `zi` to expand to `z -i` where it failed to work properly.

Concrete method to repair this is to `abbr --erase zi`.
